### ISSUE TITLE
[Bug]: Multi formulas.  Cannot read properties of null (reading 'setState')

### ISSUE THREAD

**Issue by Paqura** [handsontable/handsontable#10386]
### Describe the bug

After changing the values, the formula throws an error.

### Video/Screenshots

[Screencast from 29.05.2023 15:01:56.webm](https://github.com/handsontable/handsontable/assets/22657076/aecf7126-7d1c-47f8-9f00-633dcf4a6783)

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/naf82gcs/

### Handsontable version

12.3.3

### Your environment

any browser

**Comment by Paqura** [comment]
After update to 12.4.0 works fine.

**Comment by adrianszymanski89** [comment]
Hi @Paqura 

I just wanted to suggest it as we fixed this issue there. I will close this issue then.

**Comment by Paqura** [comment]
Still happens @adrianszymanski89 

https://codesandbox.io/p/sandbox/wizardly-dream-n4t04t?file=%2Fsrc%2FApp.tsx%3A7%2C35

**Comment by Paqura** [comment]
@adrianszymanski89 could we reopen this issue?

**Comment by Paqura** [comment]
@adrianszymanski89 If there are any options to "hack" this bug, please write.

**Comment by adrianszymanski89** [comment]
Hi @Paqura 

I found the solution. It seems there is a problem if you try to update the data through the state manager if you define the HyperFormula instance externally. If you reference it directly, then everything works fine. Until we investigate it further with our HyperFormula developer, I would recommend implementing this solution like this:

https://jsfiddle.net/handsoncode/y50gus6v/

**Comment by Paqura** [comment]
Hi @adrianszymanski89  
But it still doesn't work with sheetName with your solution

https://jsfiddle.net/wdnkL63s/

**Comment by Bboyredstar** [comment]
@adrianszymanski89 I am also facing a similar problem, I have multiple instances of a table. If I change the value of a cell on which other cells depend, and then clear the cell via backspace, I get the following error: 
<img width="639" alt="image" src="https://github.com/handsontable/handsontable/assets/50084897/1e6328ad-5478-44b6-88a6-b7f60eda7d87">

Any chance to solve it?  
Is there any known pattern to avoid this error now?
Thanks

**Comment by adrianszymanski89** [comment]
Hi @Bboyredstar 

Can you please share your current implementation?

**Comment by Bboyredstar** [comment]
@adrianszymanski89 Hi!
Unfortunately, I can't because of NDA, I can share a video where I reproduct this bug.

I add a value to the cell that the formula depends on. Then I press backspace and get this error. From my observations, if I put the last table at the very first place in the table array, this error does not occur. 

https://github.com/handsontable/handsontable/assets/50084897/9d2ae970-c901-473d-82bf-00722d9f9315

Unfortunately I can not find a specific cause, I removed custom cell renderers, changed beforeKeyDown hook to put an empty string instead of null, but still get this error.

I use:

 **"react": "^17.0.2"**
 **"@handsontable/react": "^13.1.0"**
**"handsontable": "^13.1.0"**
**"hyperformula": "^2.5.0"**

Thank you

**Comment by adrianszymanski89** [comment]
Hi @Bboyredstar 

Thank you for the video. 

> Unfortunately, I can't because of NDA

I asked just about the implementation of Handsontable + HyperFormula, preferably in a minified example where the issue is replicable. I will try to reproduce it on my own, but knowing the settings you have would be helpful.

**Comment by Bboyredstar** [comment]
@adrianszymanski89 I understand your point, but even so I can't do a small example, as the logic is quite complex and it's unlikely I can fully transfer it into an isolated example. We use several custom editors, and there are many places that would be hard to transfer out of context. So unfortunately the only thing I can say is that the problem seems to be related to the custom cell editor, if you turn it off, specifically, the problem goes away. Sometimes there is an error when re-rendering a page that contains tables. 
I can share with you editor code if it might help.

**Comment by adrianszymanski89** [comment]
@Bboyredstar 

I understand. Please share as much code as possible, and then I'll try to recreate this behavior myself.

**Comment by Bboyredstar** [comment]
@adrianszymanski89 I believe I got it: https://codesandbox.io/p/sandbox/demo-r4ysfn?file=%2Fsrc%2Fdata.js%3A8%2C4&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrg6nu6900063b6k35cli7ei%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrg6nu6900023b6khdkrf6nl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrg6nu6900033b6kl25mm4h7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrg6nu6900053b6khwdpjg70%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrg6nu6900023b6khdkrf6nl%2522%253A%257B%2522id%2522%253A%2522clrg6nu6900023b6khdkrf6nl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrgbinv600023b6qua3bw3em%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A4%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A4%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fdata.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrgbinv600023b6qua3bw3em%2522%257D%252C%2522clrg6nu6900053b6khwdpjg70%2522%253A%257B%2522id%2522%253A%2522clrg6nu6900053b6khwdpjg70%2522%252C%2522activeTabId%2522%253A%2522clrgd490702g03b6q4bx5wweu%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clrgd490702g03b6q4bx5wweu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrg6nu6900033b6kl25mm4h7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrg6nu6900033b6kl25mm4h7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

Please check reproduction steps:

https://github.com/handsontable/handsontable/assets/50084897/9df6e95e-630c-46fa-aa87-09499247768e

**Comment by adrianszymanski89** [comment]
Hi @Bboyredstar 

Thank you. I will check it and get back to you.

**Comment by adrianszymanski89** [comment]
Hi @Bboyredstar 

I checked your demo and was able to reproduce the issue. It's hard to tell where exactly the problem lies, so it will need to be investigated by our developers more. I'll update this topic once we start working on this.

**Comment by Bboyredstar** [comment]
@adrianszymanski89 Hi there! Do you have any updates for this issue?

**Comment by adrianszymanski89** [comment]
Hi @Bboyredstar 

This issue is in our backlog but has yet to be worked on. I'll update you once it's done.

**Comment by Bboyredstar** [comment]
@adrianszymanski89 Hello! 
I faced the same problem but with another formula: 

https://github.com/user-attachments/assets/7db9fe70-0d50-4520-8260-c096486190dc


Is there any way we can catch this error so that the table doesn't crash completely?

Demo: 
https://codesandbox.io/p/sandbox/demo-r4ysfn?file=%2Fsrc%2Fdata.js%3A11%2C1-24%2C8&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrg6nu6900063b6k35cli7ei%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrg6nu6900023b6khdkrf6nl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrg6nu6900033b6kl25mm4h7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrg6nu6900053b6khwdpjg70%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrg6nu6900023b6khdkrf6nl%2522%253A%257B%2522id%2522%253A%2522clrg6nu6900023b6khdkrf6nl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrgbinv600023b6qua3bw3em%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fdata.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A24%252C%2522endColumn%2522%253A8%257D%255D%257D%252C%257B%2522id%2522%253A%2522clyse0jr600023b6mni62u8i6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A38%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A38%252C%2522endColumn%2522%253A25%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrgbinv600023b6qua3bw3em%2522%257D%252C%2522clrg6nu6900053b6khwdpjg70%2522%253A%257B%2522id%2522%253A%2522clrg6nu6900053b6khwdpjg70%2522%252C%2522activeTabId%2522%253A%2522clrgd490702g03b6q4bx5wweu%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clrgd490702g03b6q4bx5wweu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrg6nu6900033b6kl25mm4h7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrg6nu6900033b6kl25mm4h7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by adrianszymanski89** [comment]
Hi @Bboyredstar 

Thank you for letting us know. I can't check it properly today, as CodeSandbox has some serious performance issues, so I'll look at this after the weekend. However, I think the reason for this error is the same as initially reported so it has to be fixed at the core.

**Comment by Bboyredstar** [comment]
@adrianszymanski89 Thank you for your response. Any chance you know an approximate time when this will be picked up for work?

**Comment by adrianszymanski89** [comment]
@Bboyredstar 

It still needs to be added to our roadmap. I will update you once it's planned for fixing.

**Comment by kolyasya** [comment]
@adrianszymanski89 do you know if this one was fixed?

**Comment by adrianspdev** [comment]
Hi @Paqura, thanks for reporting this.

I verified the bug against the current develop branch (Handsontable 17.x). The error no longer reproduces.

Repro setup:
- 12.3.3 + @handsontable/react@12.4.0 + HyperFormula 2.4 (matching the original fiddle): Uncaught TypeError: Cannot read properties of null (reading 'setState') thrown on setData1 — confirmed.
- 17.0.1 + @handsontable/react-wrapper@17.0.1 + HyperFormula 3.0: setData1 updates Sheet1, cross-sheet formulas in Sheet2 recompute correctly, no error.

The root cause was addressed in #11474 (refactor of the Formulas plugin's data-load path).

Closing this issue as resolved. Please reopen if you still hit it on a recent version with a minimal repro.
