### ISSUE TITLE
[Bug]: The first character automatically converts to an English letter in Japanese

### ISSUE THREAD

**Issue by jonghoonleeee** [handsontable/handsontable#10773]
### Describe the bug

I encountered a problem when I input Japanese.
I attempt to type in Japanese, the first character automatically converts to an English letter.
For instance, when I try to write “あああああ“, it appears as “aああああ” in the cell. Similarly, “漢字” becomes “kあんじ“, and “年” is altered to “tおし“. This issue significantly impacts the usability of Handsontable for Japanese language inputs.
Could you please advise on any quick fixes or solutions that are available?

### Video/Screenshots

![da9f34495369a52d06103908980c4450](https://github.com/handsontable/handsontable/assets/25731294/777fc822-1888-4748-8f65-2eed00e7a176)

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/api/post/library/pure/

### Handsontable version

handsontable 14.1.0

### Framework version

vue 3.4.15

### Your environment

MacOS + Chrome

**Comment by adrianszymanski89** [comment]
Hi @jonghoonleeee 

Thank you for reporting this. Can you please tell me which Japanese dialect you use? I was able to reproduce the issue with Hiragana-Romaji on macOS.

**Comment by jonghoonleeee** [comment]
Hi @adrianszymanski89 
Thank you for reproducing it. I am using the same one.

**Comment by adrianszymanski89** [comment]
Hi @jonghoonleeee 

There's one solution that might help here. Can you please try to set the option `imeFastEdit: true` in your configuration object?

**Comment by HJeong1200** [comment]
Hi @adrianszymanski89 

Just to let you know a similar issue with Korean keyboard layout.
Typing "가나다" results in "ㄱㅏ나다" so the first letter does not change in Engilsh but the first letter is not composed with the latter one which is a bug.
imeFastEdit: true fixes the issue in this case.

Using MacOS + Chrome + Handsontable v14.1.0

<img width="366" alt="스크린샷 2024-02-13 오후 9 30 14" src="https://github.com/handsontable/handsontable/assets/110910408/b8738d67-f2a2-4660-9727-ee2006db6b95">

**Comment by adrianszymanski89** [comment]
Hi @HJeong1200 

Thank you for letting me know. This option was added to solve this problem, so I'm glad it works as intended.

**Comment by jonghoonleeee** [comment]
@HJeong1200 @adrianszymanski89 
Thank you for letting me know.

Thank you for informing me.

When I added the `imeFastEdit: true `option in the Handsontable documentation, it worked correctly. However, it does not work in the code I am working on. After removing the contextMenu option, it started working properly. Does this mean that using both contextMenu and imeFastEdit options simultaneously causes it not to work?

**Comment by adrianszymanski89** [comment]
Hi @jonghoonleeee 

Thank you for the update. I tried with a custom context menu, but it still works correctly in my case. I tested it with this example: https://jsfiddle.net/handsoncode/nt68ejhq/. Can you please check if it doesn't work for you also here?

**Comment by jonghoonleeee** [comment]
Hi @adrianszymanski89 

Thank you for trying.

I tried adding a context menu on the following page, but it seems not to be working. What could be the difference? 
example: https://jsfiddle.net/c7swtk8g/7/

**Comment by AMBudnik** [comment]
Hi @jonghoonleeee I also tried to replicate the issue with Japanese-romanji keyboard and did not get this issue.

**Comment by jonghoonleeee** [comment]
Hi@AMBudnik  
Thank you for trying.

Have you tried inputting Japanese text on this page(https://jsfiddle.net/1fvd2seu/6/)? 
I attempted it on Chrome 121, Edge, Safari, and Mac OS Ventura 13, but noticed that the initial characters of Japanese text were automatically converted to Roman characters.

**Comment by jonghoonleeee** [comment]
Hi @AMBudnik  
Thank you for trying.

Have you tried inputting Japanese text on this page(https://jsfiddle.net/1fvd2seu/6/)? 
I attempted it on Chrome 121, Edge, Safari, and Mac OS Ventura 13, but noticed that the initial characters of Japanese text were automatically converted to Roman characters.

**Comment by AMBudnik** [comment]
I was able to replicate the issue, but only if I switched to Japanese after the table was loaded. Please check this video.

![Kapture 2024-02-16 at 09 33 43](https://github.com/handsontable/handsontable/assets/10757813/a2e80f59-ca5b-47f2-a6d6-833561f643ae)


1st attempt is in my standard keyboard (for me it's polish) 
2nd one (where the issue is replicable) is switching to Janapese-Romanji without refreshing the page
3rd one is Janapese-Romanji but with a new refresh of the page (the result is correct).

Does that work for you the same? Or does it also happen when you have Janapese-Romanji and after page refresh?

**Comment by jonghoonleeee** [comment]
@AMBudnik 


The issue occurs only in Japanese-Romanji. It inputs correctly when refreshing the page, but the problem occurs again afterward.

Upon refreshing the page
![501449d127a9bb74697647fe8eb64953](https://github.com/handsontable/handsontable/assets/25731294/95a006d5-dd31-4379-9d82-853f4379e5db)

After refreshing the page
![aa40763ec113f22a20ef79eb94dd7cdc](https://github.com/handsontable/handsontable/assets/25731294/896180f7-d6e2-4339-8b7a-a62cc20a706b)

**Comment by AMBudnik** [comment]
Thank you for feedback @jonghoonleeee I have reported the issue internally and will notify as soon as we fix it.

**Comment by huangshuwei** [comment]
> @HJeong1200 @adrianszymanski89 Thank you for informing me. 谢谢你通知我。
> 
> When I added the imeFastEdit: true option in the Handsontable documentation, it worked correctly. However, after adding the contextMenu option, it did not work.当我在 Handsontable 文档中添加 imeFastEdit: true 选项时，它工作正常。然而，添加contextMenu选项后，它不起作用。
> 
> It seems that using both contextMenu and imeFastEdit options simultaneously does not work.看来同时使用 contextMenu 和 imeFastEdit 选项不起作用。 ![06fd115349455577472973d9306c490b](https://private-user-images.githubusercontent.com/25731294/304622492-ee1634d5-414e-448f-915c-545711fff1a7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTQwNzgsIm5iZiI6MTcwOTgxMzc3OCwicGF0aCI6Ii8yNTczMTI5NC8zMDQ2MjI0OTItZWUxNjM0ZDUtNDE0ZS00NDhmLTkxNWMtNTQ1NzExZmZmMWE3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEyMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNjBhNjU3OGUzYWE1MmI3MjljYzhmOGE3YWRiMWJmZGVjYTZjZDQwMWFkOTJmMGQwNmVkMjE4NjA4NjExMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EkzQcAGnRDNcMPgZQO1NNXv8_D-1WT6QAdziZKOzWk0) [ ![06fd115349455577472973d9306c490b](https://private-user-images.githubusercontent.com/25731294/304622492-ee1634d5-414e-448f-915c-545711fff1a7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTQwNzgsIm5iZiI6MTcwOTgxMzc3OCwicGF0aCI6Ii8yNTczMTI5NC8zMDQ2MjI0OTItZWUxNjM0ZDUtNDE0ZS00NDhmLTkxNWMtNTQ1NzExZmZmMWE3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEyMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNjBhNjU3OGUzYWE1MmI3MjljYzhmOGE3YWRiMWJmZGVjYTZjZDQwMWFkOTJmMGQwNmVkMjE4NjA4NjExMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EkzQcAGnRDNcMPgZQO1NNXv8_D-1WT6QAdziZKOzWk0) ](https://private-user-images.githubusercontent.com/25731294/304622492-ee1634d5-414e-448f-915c-545711fff1a7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTQwNzgsIm5iZiI6MTcwOTgxMzc3OCwicGF0aCI6Ii8yNTczMTI5NC8zMDQ2MjI0OTItZWUxNjM0ZDUtNDE0ZS00NDhmLTkxNWMtNTQ1NzExZmZmMWE3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEyMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNjBhNjU3OGUzYWE1MmI3MjljYzhmOGE3YWRiMWJmZGVjYTZjZDQwMWFkOTJmMGQwNmVkMjE4NjA4NjExMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EkzQcAGnRDNcMPgZQO1NNXv8_D-1WT6QAdziZKOzWk0) [ ](https://private-user-images.githubusercontent.com/25731294/304622492-ee1634d5-414e-448f-915c-545711fff1a7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTQwNzgsIm5iZiI6MTcwOTgxMzc3OCwicGF0aCI6Ii8yNTczMTI5NC8zMDQ2MjI0OTItZWUxNjM0ZDUtNDE0ZS00NDhmLTkxNWMtNTQ1NzExZmZmMWE3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEyMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNjBhNjU3OGUzYWE1MmI3MjljYzhmOGE3YWRiMWJmZGVjYTZjZDQwMWFkOTJmMGQwNmVkMjE4NjA4NjExMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EkzQcAGnRDNcMPgZQO1NNXv8_D-1WT6QAdziZKOzWk0)

Chinese input also has the same problem：

https://github.com/handsontable/handsontable/assets/6047141/8a98f9f8-ebec-4037-97cc-65ce41e0fb94

But it works in version 13.1. I think it should be related to the update on 14.1

**Comment by adrianszymanski89** [comment]
Hi @huangshuwei 

Recently, we released a new version of Handsontable, 14.2, and when I checked this issue, I couldn't replicate it anymore. Can you please tell me if that's also the case on your side with 14.2?

**Comment by huangshuwei** [comment]
@adrianszymanski89 
Yes, this issue also exists in version 14.2 .
This is an example of version 14.2:https://jsfiddle.net/d1ur2yne/

**Comment by adrianszymanski89** [comment]
@huangshuwei 

Thank you for the update. I hope we will have a fix for this soon.

**Comment by huangshuwei** [comment]
Hi. I have found that upgrading to the latest version(14.3.0) still has this problem. Is there a repair plan for it?

**Comment by youhogeon** [comment]
I haven't tested other languages, but I'll tell you based on Korean input.

First of all, this problem occurs from 14.0 to 14.3. (It operates normally in 13.x.)

※ Note: In Korean, the letter “가” can be entered by entering “ㄱ” and then “ㅏ”.

If imeFastEdit is false, "rㅏ" is always entered. (However, if you double-click the cell and then type, it will be entered normally.)

The problem occurs intermittently when imeFastEdit is true. If you type quickly, "rㅏ" is entered, and if you type leisurely, "가" is entered.

**Comment by youhogeon** [comment]
@adrianszymanski89

I haven't tested other languages, but I'll tell you based on Korean input.

First of all, this problem occurs from 14.0 to 14.3. (It operates normally in 13.x.)

※ Note: In Korean, the letter “가” can be entered by entering “ㄱ” and then “ㅏ”.

If imeFastEdit is false, "rㅏ" is always entered. (However, if you double-click the cell and then type, it will be entered normally.)

The problem occurs intermittently when imeFastEdit is true. If you type quickly, "rㅏ" is entered, and if you type leisurely, "가" is entered.

**Comment by youhogeon** [comment]
The problem was significantly improved when the debounce-related code was removed from refocusToEditorTextarea. (It doesn't work perfectly, but it's a lot better.)

Is the code for debounce added to improve performance? Or is there another reason why debounce should not be removed?

https://github.com/handsontable/handsontable/blob/develop/handsontable/src/focusManager.js

### before
```
  refocusToEditorTextarea(delay = this.#refocusDelay) {
    const refocusElement = this.getRefocusElement();

    // Re-focus on the editor's `TEXTAREA` element (or a predefined element) if the `imeFastEdit` option is enabled.
    if (
      this.#hot.getSettings().imeFastEdit &&
      !this.#hot.getActiveEditor()?.isOpened() &&
      !!refocusElement
    ) {
      if (!this.#debouncedSelect.has(delay)) {
        this.#debouncedSelect.set(delay, debounce(() => {
          refocusElement.select();
        }, delay));
      }

      this.#debouncedSelect.get(delay)();
    }
  }
```

### after
```
  refocusToEditorTextarea(/* delay = this.#refocusDelay */) {
    const refocusElement = this.getRefocusElement();

    // Re-focus on the editor's `TEXTAREA` element (or a predefined element) if the `imeFastEdit` option is enabled.
    if (
      this.#hot.getSettings().imeFastEdit &&
      !this.#hot.getActiveEditor()?.isOpened() &&
      !!refocusElement
    ) {
//      if (!this.#debouncedSelect.has(delay)) {
//        this.#debouncedSelect.set(delay, debounce(() => {
          refocusElement.select();
//        }, delay));
//      }

//      this.#debouncedSelect.get(delay)();
    }
  }
```


I don't think this is a normal solution. It's just a temporary measure. I hope this will be of some help to people who are experiencing the same problem as me.

**Comment by adrianszymanski89** [comment]
Hi @youhogeon 

Thank you for the additional details. Our developers will investigate, and I'll update you once we have feedback from them.

**Comment by AMBudnik** [comment]
Hi @huangshuwei @jonghoonleeee @youhogeon @HJeong1200 We did some improvements in v14.4.0 here https://github.com/handsontable/handsontable/pull/10947.

Could you please update to v14.4.0 and let us know if the issue is still replicable?

**Comment by youhogeon** [comment]
@AMBudnik awesome! As soon as I get to work (about 15 hours later), I will test it and leave the results.

**Comment by youhogeon** [comment]
@AMBudnik 

First, we sincerely thank you for your interest in this issue and your efforts to resolve it.
The results of my testing are below.

When imeFastEdit is false (default)
The first letter is still “always” typed alphabetically.
(However, if you press F2 or Enter to "open" the editor and then enter it, the input will be entered normally.)

When imeFastEdit is true
It has improved greatly compared to 14.3.0.
However, it is still often typed alphabetically (especially when you finish typing and move on to the next line quickly).

(Similarly, if you press F2 or Enter to "open" the editor and then type, the input will be entered normally.)



https://github.com/handsontable/handsontable/assets/31335146/451aa61b-63a8-4c31-b814-f7f1bceb5931



I am attaching a video that reproduces the situation.
In the left column, <<ㄱ - enter - ㄴ - enter - ㄷ - enter ...>> is entered,
The right column is entered after pressing enter twice to open the editor, such as <<ㄱ - enter - enter(to open editor) - ㄴ - enter - enter - ㄷ - enter - enter - ...>>.


[summary]
* When you press enter twice, it operates abnormally regardless of the imeFastEdit value and version (14.3.0 and 14.4.0). (It is Korean ime, but alphabets are entered)
* Both 14.3.0 and 14.4.0 behave abnormally when imeFastEdit is false.
* 14.4.0 is slightly better than 14.3.0 when imeFastEdit is true, but still occasionally behaves abnormally

**Comment by youhogeon** [comment]
https://github.com/handsontable/handsontable/assets/31335146/c25006d1-da80-4031-996f-5801ad7f996d

This (obviously) also happens in the official examples on the handsontable main page.

Also, I am attaching a jsfiddle link for the example used in the video above.

* 14.3.0 false : https://jsfiddle.net/rmd3pwyf/
* 14.3.0 true : https://jsfiddle.net/f30uLy27/1/
* 14.4.0 false : https://jsfiddle.net/teouyhrq/1/
* 14.4.0 true https://jsfiddle.net/aqntrc68/3/

I will also try to find the code that causes this phenomenon to occur.
Once I solve the problem, I will leave the solution here for the benefit of countless Koreans, Chinesses, and Japanesenesses.

**Comment by AMBudnik** [comment]
> I will also try to find the code that causes this phenomenon to occur.
Once I solve the problem, I will leave the solution here for the benefit of countless Koreans, Chinesses, and Japanesenesses.

Thank you so much, @youhogeon 

We will also retest that internally.

**Comment by youhogeon** [comment]
@AMBudnik 

I set a keydown event on the textarea (this.TEXTAREA) and container (passed as the first argument to the Handsontable constructor) in textEditor and checked the order in which the code is executed.

When entering << ㄱ - enter - ㄱ - enter - ㄱ - enter - ... >> within the table, the code was executed in the following order.

(Cell is selected) - Editor's prepare method is called - (Press ㄱ key) - TEXTAREA's keydown(code: ㄱ) event occurs - Container's keydown event occurs - Editor's focus method is called - (Press the enter key) - The keydown (code: enter) event of the TEXTAREA occurs - The keydown event of the container occurs - The row below is selected and the editor's prepare method is called.


However, due to a bug, it was confirmed that when r is entered instead of ㄱ, the keydown event does not occur in the textarea, but only the keydown event in the container occurs.

(Cell is selected) - Editor's prepare method is called - (Press ㄱ key) - Keydown event of container occurs - Editor's focus method is called - (Enter key is pressed) - TEXTAREA's keydown(code) : enter) event occurs - The keydown event of the container occurs - The row below is selected and the editor's prepare method is called.


I decided that this was because the textarea was not prepared correctly, so it did not receive the keydown event.
I solved it by adding this.TEXTAREA.select() in the prepare method of textEditor (above `this.refreshDimension(true)`).

```
...
if (!cellProperties.readOnly) {
  this.TEXTAREA.select() // <- here
  this.refreshDimensions(true); 

  ...
}
```


Then with imeFastEdit set to true, the bug no longer reoccurred.
However, there are also limitations.

1. Even if imeFastEdit is false, the problem is solved to some extent, but alphabets are still entered intermittently.
2. When imeFastEdit is false, if you select a cell with the mouse and then try to input, the first letter is “always” entered as an alphabet.
3. I am not convinced that selecting the textarea in the prepare method is likely to cause other side effects.

**Comment by huangshuwei** [comment]
> Hi @huangshuwei @jonghoonleeee @youhogeon @HJeong1200 We did some improvements in v14.4.0 here #10947.
> 
> Could you please update to v14.4.0 and let us know if the issue is still replicable?

@AMBudnik Thank you for your efforts. Everything has been working since I switched to version 14.4 .

Here is the demo effect of Chinese input:
https://github.com/handsontable/handsontable/assets/6047141/b83f1956-e13f-4087-81af-d03cc6ba83ff

**Comment by retrop5** [comment]
Hi, I have been waiting for an update on this issue for a while.
Since @huangshuwei mentioned his issue being resolved in 14.4 I tested it out again (Japanese Language) on my local env.
Unfortunately, for Japanese the issue still persists.

Here is a recording for it,

https://github.com/handsontable/handsontable/assets/74864964/02a9773a-d883-4705-94e3-6d362d7727d8

Here is the table configuration,

```
hot = new Handsontable(container, {
	licenseKey: 'non-commercial-and-evaluation',
	data: data,
          language: 'ja-JP',
	manualRowResize: true,
	rowHeaders: true,
	rowHeights: 50,
	className: 'htMiddle',
	renderer: detailRenderer,
	fillHandle: false,
	preventScrolling: false,
	hiddenColumns: {columns: [0,9,10,11,12, 13, 14, 15, 16, 17, 18, 20, 21]},
	filters: true,
	dropdownMenu: ['filter_by_condition', 'filter_by_value', 'filter_action_bar'],
	columns: [	
		//redacted data
	],
          manualColumnResize: true,
          manualRowResize: true,
          renderAllRows:true,
          stretchH: 'all',
	afterChange: getChangedRows,
	afterGetRowHeader: function(col, TH) {
		TH.className = 'htMiddle'
	},
	cells: function (row, col) {
		var cellProperties = {};
		cellProperties.renderer = detailRenderer;
		return cellProperties;
	}
});
```

My handsontable version,
```
 * Version: 14.4.0
 * Release date: 11/06/2024 (built at 06/06/2024 10:09:45)
```

**Comment by AMBudnik** [comment]
Thank you for the feedback @retrop5 

We tested it in many ways and struggled to find the case of the issue. We have one Client (not in this thread) confirming that the issue is solved for Japanese. They tested it on standard settings (only `colHeaders` and `rowHeaders` are on). Are you able to replicate the same issue having only those settings as well?

**Comment by retrop5** [comment]
Hi @AMBudnik I tested it on standard settings and it works fine, but since it doesn't work for the setting I have shown above, let me see where it is causing an issue (assuming that my custom renderer is playing priority games). However, I will test it in detail and let you know my results over the weekend, hope that's fine.

**Comment by youhogeon** [comment]
@retrop5 Does this really work? I just installed the Japanese IME (provided by Windows) and tested it, but the "first letter bug" still exists.

https://jsfiddle.net/teouyhrq/1/

### My testing procedure
1. Select one cell with the mouse. (Be careful not to double-click to enter editing mode. Proceed without the cursor blinking.)
2. Check if the Japanese IME is in hiragana mode
3. Enter aaaa
4. (Result) aあああ is entered.


Please let me know if my testing method is wrong.

I'm not sure why it worked normally in @retrop5 and @AMBudnik's tests. (This is most likely due to my lack of understanding of Japanese.)

**Comment by retrop5** [comment]
Hi guys, I am sorry It took so long to reply back, I was surprised when @youhogeon commented about the issue persisting, so I went ahead and tested it again, looks like the issue still persists, I'm sorry for the incorrect update. Please have a look at this sample video I created. 

# When `imeFastEdit` is not set
https://github.com/handsontable/handsontable/assets/74864964/4d434edc-f290-42a6-aa1d-a7d6f1f9ae5a

NOTE: 
1. At 00:09 I have refreshed the page to show that specific case as well.
### Code:
```
$(function(){
    const hot = new Handsontable(document.getElementById('targetItem'), {
        licenseKey: 'non-commercial-and-evaluation',
        data: [
            {KEY:1, NAME:'テスト1', VALUE:'1'},
            {KEY:2, NAME:'テスト2', VALUE:'2'},
            {KEY:3, NAME:'テスト3', VALUE:'3'},
            {KEY:4, NAME:'テスト4', VALUE:'4'},
            {KEY:5, NAME:'テスト5', VALUE:'5'},
        ],
        height: $(window).height() - 230,
        manualRowResize: true,
        rowHeaders: true,
        fillHandle: false,
        hiddenColumns: {columns: [0]},
        filters: true,
        comments: {displayDelay: 500,},
        dropdownMenu: ['filter_by_condition', 'filter_by_value', 'filter_action_bar'],
        columns: [
            {data:'KEY', title:'', width:50, readOnly:true},
            {data:'NAME', title:'名前', width:300},
            {data:'VALUE', title:'値', width:100},
        ],
    });
});
```
# When `imeFastEdit` is set to `true`

https://github.com/handsontable/handsontable/assets/74864964/f5812310-854f-4742-bbbb-29baa0a33f42

NOTE: 
1. At 00:11 I have refreshed the page to show that specific case as well.

### Code:
```
$(function(){
    const hot = new Handsontable(document.getElementById('targetItem'), {
        licenseKey: 'non-commercial-and-evaluation',
        data: [
            {KEY:1, NAME:'テスト1', VALUE:'1'},
            {KEY:2, NAME:'テスト2', VALUE:'2'},
            {KEY:3, NAME:'テスト3', VALUE:'3'},
            {KEY:4, NAME:'テスト4', VALUE:'4'},
            {KEY:5, NAME:'テスト5', VALUE:'5'},
        ],
        height: $(window).height() - 230,
        manualRowResize: true,
        rowHeaders: true,
        fillHandle: false,
        hiddenColumns: {columns: [0]},
        filters: true,
        comments: {displayDelay: 500,},
        dropdownMenu: ['filter_by_condition', 'filter_by_value', 'filter_action_bar'],
        columns: [
            {data:'KEY', title:'', width:50, readOnly:true},
            {data:'NAME', title:'名前', width:300},
            {data:'VALUE', title:'値', width:100},
        ],
        imeFastEdit: true,
    });
});
```

@AMBudnik would this be of any help?

**Comment by youhogeon** [comment]
Excuse me, but can you tell me the status of the issue?
If it is on hold, I will investigate the cause a little more.

**Comment by adrianszymanski89** [comment]
Hi @jonghoonleeee 

Not yet. We are still unable to reproduce the issue fully on our side. We will update you on this issue as soon as we have more information.

**Comment by shusuke919** [comment]
We have confirmed that the problem is clear for both Microsoft and MAC.
    "@handsontable/react": "^14.6.1",

**Comment by adrianszymanski89** [comment]
Hi @shusuke919 

By cleared up, do you mean the issue is no longer replicable?

**Comment by youhogeon** [comment]
My Korean and Japanese IME is not working well in `14.6.1`

https://jsfiddle.net/kqwno5dz/

In Korean IME
`press ㄱ(a key) -> press enter -> and repeat as fast as you can (about 2~3 times for a second)`

In Japanese IME
`press ㄱ(a key) -> press enter twice -> and repeat as fast as you can`

**Comment by adrianszymanski89** [comment]
Hi @youhogeon 

Can you please also attach a video recording of the results you get? When I press the Enter key twice, the first letter is chosen from the list, the editor is closed, and the selection moves to the row below.

**Comment by youhogeon** [comment]
@adrianszymanski89 

https://github.com/user-attachments/assets/432383bd-28d8-4f9e-bfda-a5d611bf806b

I apologize for the late response.

I marked the keys I pressed on the left side of the video.

I recommend you test with Korean IME, not Japanese. (easier to reproduce the bug and easier to debug)

**Comment by adrianszymanski89** [comment]
Hi @youhogeon 

Thank you for the video. Unfortunately, we are still not able to reproduce this situation. My colleague and I both tried various setups of Korean and Japanese keyboards. I also tried it on Windows, as I noticed that you are using it, but it didn't change anything. 

We will keep trying, and I'll keep you updated.

**Comment by retrop5** [comment]
@adrianszymanski89 can you please share the layout of japanese keyboard you are using?
For information, most of the systems in Japan use Microsoft IME (on windows devices) or Shift-JIS

Unfortunately I am not aware of how it works with Korean, maybe @youhogeon can pitch in.
If this still persists, we would be happy to hop on a google meet to explain/replicate what the issue could be.

Let me know if I can be of any help.

**Comment by youhogeon** [comment]
I, too, used the Microsoft default IME.

@adrianszymanski89  If you don't mind me asking, can you share the video you failed to reproduce?
(With the IME icon in the taskbar tray)

I'd like to see what's different from mine.

**Comment by adrianszymanski89** [comment]
Hi @youhogeon 

I tested all of the variants of the Korean and Japanese keyboards today and still can't reproduce the issue.

As for the way I tested it is exactly the same as the one you showed in your video.

**Comment by youhogeon** [comment]
Thank you for your efforts to resolve the issue.
I'll comment again if there's any further progress on reproducing/resolving the issue.

We wish you a happy holiday season.

**Comment by pzgz** [comment]
can confirm `imeFastEdit` is working fine with Chinese input, thanks a lot for all of your efforts.

**Comment by retrop5** [comment]
@adrianszymanski89 
The `imeFastEdit` is working for me as well, I'd like to apologize as I had misconfigured the definitions when testing on `v14.6.1`. I tried it on a fiddle last week and it worked perfectly fine.

**Comment by adrianszymanski89** [comment]
Hi @youhogeon 

This topic was previously about the Japanese keyboard layouts, but we were unable to reproduce it under any circumstances. Could you please specify whether the problem with the Korean layout is reproducible in the same manner as the original issue?

**Comment by youhogeon** [comment]
@adrianszymanski89 
The reproduction method is described in this comment.
https://github.com/handsontable/handsontable/issues/10773#issuecomment-2179794225

Thank you.

**Comment by youhogeon-meritz** [comment]
Thank you @adrianszymanski89 .

With the [Korean IME enabled](https://learn.microsoft.com/en-us/globalization/input/korean-ime#add-support-for-korean-input), try the following experiment in the demo on the main page at https://handsontable.com/

1. With cell input deactivated (immediately after clicking a cell once), type `r`, `k`, `r`, `k`
2. With cell input enabled (after clicking the cell and pressing `F2`), type `r`, `k`, `r`, `k`

In case 1, `rㅏ가` will be input. In case 2, `가가` will be input. Case 2 is correct. Case 1 is problematic because the composition did not occur correctly.

**Comment by adrianszymanski89** [comment]
@youhogeon-meritz 

Thank you, I will try that.
