### ISSUE TITLE
Vertical scroll -> missalignment of row-headers

### ISSUE THREAD

**Issue by Lavos96** [handsontable/handsontable#11397]
### Describe the bug

![Image](https://github.com/user-attachments/assets/d18a1bc8-dff1-484d-b631-000e01b20119)

When I have a table that has horizontal and vertical scrolls, and I scroll the vertical scroll down, this issue occurs (missalignment of row-headers). Interestingly, if I move the horizontal scroll, the situation is fixed. It is connected to this change, I think: https://github.com/handsontable/handsontable/pull/11289

### Handsontable version

15.0.0

### Framework version

"@handsontable/angular": "15.0.0"

angular: 19.1.0

### Your environment

Chrome Version 131.0.6778.265

**Comment by adrianszymanski89** [comment]
Hi @Lavos96 

Thank you for contacting us. Please share a code demo where the problem can be replicated.

**Comment by MREStorey** [comment]
We are also seeing a similar issue with our product. From what I can see, it is demonstrable on your built in demos on the documentation site.

![Image](https://github.com/user-attachments/assets/7af1f35f-6cc9-4ce2-afff-bbeb63ff4171)

This is on a Firefox browser. On Chrome, it appears to look normal. Noting though that our problem is also in Chrome where more rows cause the row headers to slowly disappear.

**Comment by adrianszymanski89** [comment]
@MREStorey 

Do you use scaling in the browser or the OS? Scaling is the most common source of such issues.

**Comment by Lavos96** [comment]
@adrianszymanski89 Im also seeing this issue in your demo (https://handsontable.com/docs/javascript-data-grid/grid-size/#manual-resizing) 

![Image](https://github.com/user-attachments/assets/8749402c-4fa4-429f-9547-395ca5c59fa8)

And yes changing scale in my OS helped in this case but it didnt help in case of our project. I can say that there was no issue on previous version of handsontable (14.6.1) and on angular ver. 18.2.0 (maybe there is some connection, maybe this is not working correctly with angular 19+?).

**Comment by adrianszymanski89** [comment]
@Lavos96 

The Angular version shouldn't change anything here. This issue is present for some time if you zoom in/out of the viewport, so it shouldn't be connected to any specific version. Please share a demo where this can be replicated. I tried with the generic demos in the documentation, and it's only reproducible with zooming, but in all versions.

**Comment by AMBudnik** [comment]
Hi @Lavos96 @MREStorey do we have any updates regarding the subject?

**Comment by vkirienko** [comment]
It is misaligned even on main Handsontable demo page (https://handsontable.com/demo) with 100% scaling.

![Image](https://github.com/user-attachments/assets/0e9bf25d-4b62-44ab-bf7f-cbbc9deec96e)

And as soon as you start scrolling it it becomes more and more visible.

![Image](https://github.com/user-attachments/assets/81ab86c0-e585-4570-9bdd-b6b040d03f75)

Is there any solution for this?

**Comment by AMBudnik** [comment]
Hi @vkirienko are you using a Windows system with a 125% system scale?

**Comment by vkirienko** [comment]
Yes, that's correct Windows with 125% scale.

**Comment by vkirienko** [comment]
@AMBudnik I have some reservations about your root cause assessment:

1. We never received any end-user complaints before upgrading to v15.
2. I never encountered this issue myself before v15, and we’ve been using Handsontable for several years.
3. It seems illogical that scaling would only affect the first column/row and not the others. This inconsistency doesn’t make sense to me.
4. In our application, we use Handsontable across several pages, but only some experience this issue. While the settings differ slightly, this suggests that the problem lies in how Handsontable handles these settings, rather than scaling itself.

> You can try to set up rounded rowHeights values when a system scale is detected.

Even if scaling is indeed an issue, I suggest that Handsontable should detect and handle scaling internally, rather than requiring users to compensate for it.

**Comment by MREStorey** [comment]
> Hi [@Lavos96](https://github.com/Lavos96) [@MREStorey](https://github.com/MREStorey) do we have any updates regarding the subject?

Apologies for my delayed reply.

I am using Fedora 41 with 100% scaling. We've just resolved to not upgrading our Handsontable version for now because it is only present in 15.0.0.

**Comment by vkirienko** [comment]
I’m not sure if it’s related, but I removed the theme to make it more visible. As you can see, there’s a missing pixel row that causes further misalignments.

![Image](https://github.com/user-attachments/assets/a142e871-4435-47c3-b34e-08257b67442d)

Once I remove the column headers, everything looks fine, and I can’t reproduce the misalignment with any browser scaling.

![Image](https://github.com/user-attachments/assets/ce63fe19-a1bc-4481-8b36-eb76fd1df297)

**Comment by AMBudnik** [comment]
@MREStorey that should not happen on 100% browser zoom and 100% system scale. Could you please point me out how to replicate the issue? Maybe you'd be able to replicate it using any of our [documentation demos](https://handsontable.com/docs/react-data-grid/)? If so, please check the browser version you use and if there might be any add-ons altering the result. 

@vkirienko thank you for checking. We will test the header misalignment between the versions with 125%. If there is a change (for worse) that could be easy to fix.

**Comment by AMBudnik** [comment]
Hi @vkirienko @MREStorey my colleague identified the issue and reported it internally. I will updated you upon the release with a fix.

**Comment by AMBudnik** [comment]
Hey @vkirienko @MREStorey We identified some places for improvement and fixed them in this pull request https://github.com/handsontable/handsontable/pull/11465. I will update you upon release.

**Comment by vkirienko** [comment]
Thank you. I think that particular issue is fixed, I see the horizontal line now. 

But here is more - handsontable is inserted into Bookstrap card and then it's height is set so it fits screen height. 

Thank you for your help! The horizontal line issue seems to be resolved now.

However, I have another issue. I’ve inserted a Handsontable into a Bootstrap card and adjusted its height to fit the screen.

```
<div class="card">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col-auto">
                <span class="card-title"><strong>XYZ</strong></span>
            </div>
            <div class="col">
            </div>
            <div class="col-auto">
                <button type="button" class="btn btn-primary btn-xs float-end">
                    <i class="fas fa-file-excel me-2"></i>Download in Excel
                </button>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div id="divHandsontableId">
        </div>
    </div>
</div>
```

I set Chrome’s zoom to a specific percentage and refreshed the page. When I start scrolling, I notice the following issue:

![Image](https://github.com/user-attachments/assets/24f42753-3a1f-43e6-a3f5-1dfce4faa553)

When at I scroll all the way to the bottom of the grid, I see this: 

![Image](https://github.com/user-attachments/assets/5872e6dd-d7bc-41e9-905e-96386cc32bde)

**Comment by vkirienko** [comment]
Initially, I thought the issue was with **rowHeaders**, but I later noticed it was related to any fixed columns on the left. For now, if I set **fixedColumnsLeft** to 10 (which is more than the number of columns I have), the issue doesn’t occur at any zoom level.

**Comment by AMBudnik** [comment]
Hi @vkirienko 

Can I ask you to provide more details (demo, steps) on support@handsontable.com? We'd like to avoid having different issues within one Github request - then it is harder to track/close what is already fixed.

**Comment by vkirienko** [comment]
Hi, 

I tried the new version, but unfortunately, it did not resolve my misalignment issue. I must admit that none of your samples experience this issue anymore. However, in my specific case, the problem persists. I haven't had much time to investigate it thoroughly or create a reproducible example, but I believe I've narrowed it down to the row with my custom key-value dropdown list. If I'm not mistaken, it uses another Handsontable inside the cell.

Due to time constraints, I couldn't look deeper into the issue and couldn't leave it unresolved. Therefore, I changed the implementation. Instead of using rowHeaders, I choose to use a simple data column.

Below is the implementation (I believe I sourced it from StackOverflow) in case you want to investigate further.

```
class KeyValueListEditor extends Handsontable.editors.HandsontableEditor {
  prepare(row, col, prop, td, value, cellProperties) {
    super.prepare(row, col, prop, td, value, cellProperties);

    Object.assign(this.htOptions, {
      data: this.cellProperties.source,
      columns: [
        { data: 'Key' },
        { data: 'Value' }
      ],
      hiddenColumns: {
        columns: [1],
      },
      colWidths: cellProperties.width - 1,
      beforeValueRender(value, { row, instance }) {
        return instance.getDataAtRowProp(row, 'Value');
      }
    });

    if (cellProperties.keyValueListCells) {
      this.htOptions.cells = cellProperties.keyValueListCells;
    }
    if (this.htEditor) {
      this.htEditor.destroy();
    }

    this.htEditor = new Handsontable(this.htContainer, this.htOptions);
  }

  setValue(value) {
    if (this.htEditor) {
      const index = this.htEditor.getDataAtProp('Key').findIndex(id => id === Number(value));

      if (index !== -1) {
        value = this.htEditor.getDataAtRowProp(index, 'Value');
      }
    }
    super.setValue(value);
  }

  getValue() {
    const value = super.getValue();

    if (this.htEditor) {
      const labels = this.htEditor.getDataAtProp('Value');
      const row = labels.indexOf(value);

      if (row !== -1) {
        return this.htEditor.getDataAtRowProp(row, 'Key');
      }
    }

    return value;
  }
}

const keyValueListValidator = function (value, callback) {
  let valueToValidate = value;

  if (valueToValidate === null || valueToValidate === void 0) {
    valueToValidate = '';
  }

  if (this.allowEmpty && valueToValidate === '') {
    callback(true);
  }
  else {
    const isValid = this.source.find(({ Key }) => Key === value) ? true : false;
    if (isValid) {
      callback(true);
      return;
    }

    callback(this.source.find(({ Value }) => Value.toLowerCase() === value.toLowerCase()) ? true : false);
  }
};
const keyValueListRenderer = function (hot, TD, row, col, prop, value, cellProperties) {
  const item = cellProperties.source.find(({ Key }) => Key === value);

  if (item) {
    value = item.Value;
  }

  Handsontable.renderers.getRenderer('autocomplete').call(hot, hot, TD, row, col, prop, value, cellProperties);
};

Handsontable.cellTypes.registerCellType('key-value-list', {
  editor: KeyValueListEditor,
  validator: keyValueListValidator,
  renderer: keyValueListRenderer,
});

```

**Comment by AMBudnik** [comment]
Thank you for sharing the code sample, @vkirienko. However, I wasn't able to replicate the issue with the cell type mentioned in the attachment.

Here's a demo for testing https://jsfiddle.net/t06odgq2/3/. 

There must be something we're missing.

**Comment by AMBudnik** [comment]
Hi @vkirienko 

I will need to close the issue due to a lack of activity and the inability to replicate the issue.

If you'd want to get back to the subject, please let me know at suppoRT@handsontable.com
