### ISSUE TITLE
Inserting rows/cols doesn't shift cell meta data

### ISSUE THREAD

**Issue by Sphinxxxx** [handsontable/handsontable#1823]
Removing rows and columns works just fine, but inserting new ones makes meta data lose track of their cells - the meta data isn't shifted along with the cell values.

Try the following JSFiddle: http://jsfiddle.net/zq5fzegx/1/

1. Notice that the "#" cell is green and centered (because of the cell's `className` meta data).
2. Now remove the "Kia" column and the "2008" row.
    * The "#" is still green and centered as one would expect.
3. Insert a new row and a new column where the old ones were removed in step 2 (insert row above "2009" and insert column to the left of "Nissan").
    * Now, the number 11 is green and centered instead.

**Comment by TobiasBg** [comment]
This is really annoying and I'd love to see a fix for it. Without it, cell meta data is rather useless at the moment :-(

**Comment by naushadkm** [comment]
milestones are kept moving, is there any road map on this functionality. I'd love to see a fix for it. Thanks.

**Comment by kiru00** [comment]
dont mail me...plz

On Thu, Dec 24, 2015 at 2:18 PM, Naushad Kinya Moidin <
notifications@github.com> wrote:

> milestones are kept moving, is there any road map on this functionality.
> I'd love to see a fix for it. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/handsontable/handsontable/issues/1823#issuecomment-167070203>
> .
>



-- 

*Regards*

*kirankumar S*
*Mob- 9886593396*

**Comment by AMBudnik** [comment]
@kiru00 you can change your notification settings at https://github.com/settings/notifications

**Comment by krzysztofspilka** [comment]
Hey all, we've finally managed to take on this issue and it will be released in the next version (0.21.1 or 0.22.0). Sorry it took us so long.

@naushadkm @TobiasBg @Sphinxxxx @jansiegel

**Comment by naushadkm** [comment]
great!. thank you so much for your priceless efforts. @krzysztofspilka

**Comment by krzysztofspilka** [comment]
@naushadkm @TobiasBg @Sphinxxxx 

We're still working on it, not that easy though. We had to release 0.22.0 without this fix. Stay tuned, it's under intense development.

**Comment by jansiegel** [comment]
I've modified the alter methods (insering and removing rows and columns) to shift the metadata according to new row/col layout.

It doesn't, however fix this problem:


> However, I noticed an inconsistency when applying a renderer in the cells function. JSFiddle: http://jsfiddle.net/5yr3b6g7/1/
> 
> Insert a column to the left of "Kia". The greenRenderer stays on column 3; OK.
> Remove the column you inserted. greenRenderer is now "smeared" across columns 2 & 3; strange?

As the function provided in the `cells` option is triggered every time the cell is rendered, it applies the cell meta changes to each cell it was triggered on. This might cause the *smearing* effect. I think it might stay this way, as there's no way (at least none that I can think of) to prevent that from happening - if the meta was cleared every time the `cells` function is called, it would clear *all* metadata. 

For example, if I manually add a new meta property to a cell (let's call it `testProp`), and define the `cells` function, which modifies the cell's class name, every time the `cells` function is called, my `testProp` would be destroyed, and I don't think we should do that.
What do you think about it, @budnix, @krzysztofspilka?

Also, I've changed the meta cache clearing in the `updateSettings` method - now it clears only if the new settings contain `cell`, `cells` or `data` properties (as they may require modifying the existing metadata). I did is so changes not related to data would not clear cell meta.
For example, now:
```js
updateSettings({
   width: 300
});
```
will not reset cell classnames provided in the `cell` config option.

Note: this change is **backward incompatible**.

**Comment by staran** [comment]
Hi, I'm currently also stuck on this issue, I save some properties (ids, flags, ...) via setCellMeta per cell and for me it looks like the following JSFiddle (https://jsfiddle.net/5vjhgqnq/4/ - "2012" is colored, after adding a new row it is not) is even not working when using the code from the issue-1823 branch. Is there another preferred solution/workaround I could use for my use case?

**Comment by jansiegel** [comment]
@staran Are you sure you've built the `issue-1823` branch? I've tested your JSFiddle and it seems to be working fine for me.
I've updated this demo with `.js` and `.css` files built from `feature/issue-1823`. http://jsfiddle.net/5vjhgqnq/6/

**Comment by staran** [comment]
thanks for your efforts, you are right it looks good now.

**Comment by naushadkm** [comment]
After manually moving the column, Removing the column from the context menu, removes the wrong column!

please check this fiddle: http://jsfiddle.net/nkm/zq5fzegx/4/

Steps: 
1. Move the column A to the column B's position by manually dragging from the column header drag handler.
    - It successfully moves.

2. Right Click on column A and select "remove column".
   - It removes the column B.

**Comment by AMBudnik** [comment]
Confirmed, it's still there in slightly different situation that @naushadkm described.

**Comment by jansiegel** [comment]
@naushadkm, I don't think this problem is strongly related with this issue, I've started another one at #3281

**Comment by naushadkm** [comment]
@jansiegel Yes exactly. and Thanks for #3281

**Comment by AMBudnik** [comment]
I'm closing this issue as it is solved with [0.23.0](https://github.com/handsontable/handsontable/releases/tag/0.23.0) in its original description.

**Comment by yilongzhou** [comment]
@AMBudnik 
Hello, do you solve this problem now?

**Comment by AMBudnik** [comment]
Hi @yilongzhou problem described in the first post was solved with v0.23.0. During the conversation here we added related topic at #3281 (which is also closed/solved with v0.24.0) 
If there's anything that we're missing about solving this issue please share more details.

**Comment by yilongzhou** [comment]
@AMBudnik 
Hello, I have updated to the version 0.24.1. please confirm whether #3296  has been resolved.
It is still wrong.

**Comment by AMBudnik** [comment]
@yilongzhou 
Sorry that I haven't reply before. Can you please share a demo where we'll be able to replicate the issue?
