### ISSUE TITLE
Comments problem, when I have more than one handsontable in the page

### ISSUE THREAD

**Issue by hellovijayr** [handsontable/handsontable#1881]
Hi,

I've a bunch of handsontables on my page - when I try to set comments on each of the table, they don't seem to work correctly.  Please find the sample code below

http://jsfiddle.net/vijayr/os9vxuzt/

In the example above, the first table shows the comments from the second table - the comments seem to be pulled based on the table class name, instead of the id

Could you please advice?

Thank You.

**Comment by felixhagspiel** [comment]
hello @steelstyle is this fixed in 0.12.3 ? I get a context-menu problem when I use multiple handsontable instances on one page. Chrometools show the error "Uncaught TypeError: Cannot read property 'from' of undefined"  on `var cell = instance.getSelectedRange().from;` at line 10419 when I right-click inside an cell. With just one instance on the page it works fine. I added the `comments:true` option and set
```contextMenu = {
			items: {
				"commentsAddEdit":{},
				"commentsRemove":{}, ...
}
}```` to the context menu. Do I have to do anything else? I am using the full version of handsontable.

**Comment by steelstyle** [comment]
I didn't tried last version of handsontable, and I never had feedback about my pull request or saw that the file was modified so I think it will still occur.

**Comment by felixhagspiel** [comment]
Okay, too bad. Thanks for the reply anyway!

**Comment by alexyaseen** [comment]
This seems to relate to #2025

**Comment by AMBudnik** [comment]
Reproduced it also with 0.15.0-beta2 [here](https://jsfiddle.net/AMBudnik/wa5mnas5/1/).

To reproduce:
Hover over cells with comments.

**Comment by krzysztofspilka** [comment]
https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5
