### ISSUE TITLE
Ctrl key empties cell value

### ISSUE THREAD

**Issue by PartyArk** [handsontable/handsontable#2089]
Selecting a range of cells, then pressing the Ctrl key (ready to do Ctrl+C) - and the first cell selected empties itself and goes into edit mode. In fact, it doesn't have to be a range, a single cell will do.

The value is correctly copied to the clipboard. However, when I now return to the table and click anywhere on it, the cell's contents are changed to be empty.

Tried this on Firefox(35) and Chrome(40)

The Shift and the Alt keys don't do anything - surely Ctrl shouldn't either?

Otherwise, great piece of coding.

**Comment by PartyArk** [comment]
A little bit more detail - my HP keyboard is sending both keycode 17 (Ctrl) and keycode 178 (MediaStop) on Left Ctrl, and keycode 17 and keycode 92 (Win) on Right Ctrl.

Tried it with another generic keyboard and it was normal, so it's related to certain keyboards.

Neither of these bogus keydowns are in the printable ranges. Since we have the isPrintableChar function, it might be worth not giving focus unless the character is printable.

**Comment by AMBudnik** [comment]
Hi @PartyArk we fixed some bug related to Ctrl key in 0.12.6 version. Can you check if everything is working fine now?

**Comment by TheNotary** [comment]
The bug is still present on FireFox, but chrome isn't affected.  To reproduce, navigate to 
http://handsontable.com/demo/numeric.html

* Click the "year" column to highlight that whole column.  
* Hit Ctrl+C to copy the column (and release they keys)
* No just hit Ctrl, and the first cell "year" sadly will be cleared on key down.  

FF version 36.0.4
Handsome Tables 0.13.1

Btw, beautiful work on this code, it looks stunning and I like the API!

**Comment by AMBudnik** [comment]
I couldn't reproduce it on my virtual machine with FF 36 and 37. We'll take a closer took at this issue.

**Comment by TheNotary** [comment]
I just tried it in firefox in safemode (disabled addons) and got the same results, also upgraded to FF 37.0.1.  

As a note, I'm running FF in Linux Mint 17 which should behave similar to Ubuntu and somewhat similar to Debian.  I just checked IceWeasel on Rasbian and it doesn't have the bug, which makes me think either there's a problem with FF on linux mint, or it's something the matter with my LM install.  I'll test another linux mint install at work shortly.

**Comment by PartyArk** [comment]
You might want to check what keycodes your keyboard is firing- the original bug I found was caused (as per comment #2) by _two_ keycodes being fired by using the extended keys. Thanks.

**Comment by TheNotary** [comment]
I just checked another linux mint install at work and it has the same cell clearing problem.  Sadly I don't have Ubuntu anywhere, I would check if Ubuntu has the problem.  Linux Mint tries to do something to the firefox apt-get repository which might cause issues, but I thought I disabled their 'toy' build of FF on this system.  

Does anyone have an Ubuntu test VM setup?  

Also, I'm new to this repo, PartyArk, can you point me to a line where I can drop a conslose.log(keycode) line?

**Comment by nyon** [comment]
I can confirm that Ubuntu 14.04, FF 38.0, Handsontable 0.15.0-beta6 has the same problem. CTRL does clear the cell. CTRL+V does work as expected. CTRL+C does not work, since there is nothing to copy. 
On my machine, only a simple CTRL and C is sent to JS:
```
which: 17
keyCode: 17
type: "keydown"
charCode: 0
ctrlKey: true
key: "Control"
```

I'll take a deeper look into the code.

**Comment by skosch** [comment]
Confirmed that this works (the line in question is https://github.com/handsontable/handsontable/blob/master/src/editorManager.js#L94); this likely fixes #2365 as well

**Comment by vinayguthal001** [comment]
Ctrl Key,AltKey or any special key still not working on OSX/Chrome...  Like If i scroll and press command.. or try to do  scroll.. the page becomes all white

**Comment by AMBudnik** [comment]
Thank you @vinayguthal001. Confirmed, in example with <kbd>cmd</kbd> button it acts like shown below
![issue](https://cloud.githubusercontent.com/assets/10757813/8893831/504d1c30-33a1-11e5-9eec-123a3d8aea0c.gif)

**Comment by TheNotary** [comment]
Thanks everyone who worked on this!  :heart:
