### ISSUE TITLE
Handsontable is not recognising the 'overflow' value of parent container if not set as inline

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#2100]
Handsontable is not recognising the `overflow` value of parent container if the property is defined in an external stylesheet, not as an inline parameter.
This causes issues with overlays not updating positions, editors having wrong withs/heights etc.

**Comment by krzysztofspilka** [comment]
Fixed and released in v 0.12.5
See the release notes for it: https://github.com/handsontable/handsontable/releases/tag/0.12.5

**Comment by alexyaseen** [comment]
@krzysztofspilka correct me if I'm wrong, but it seems like this bug still exists. I used the scroll example jsFiddle and the only change I made is I removed the inline style and added it to the external css: http://jsfiddle.net/mogabxnf/
