### ISSUE TITLE
Comment positioning issue

### ISSUE THREAD

**Issue by iamrohitnigam** [handsontable/handsontable#2196]
I am using handsontable's comment and scroll feature, but it results in wrong positioning of comment when scrolled.

Here is [jsFiddle](https://jsfiddle.net/iamrohit18/452y4qsu/5/) of code.

Please scroll and then hover for comment, it shows comment div goes out of its position. 
I want it should come same as it comes without scrolling.

**Comment by AMBudnik** [comment]
Indeed it's a comment related bug, thanks for sharing - we added it to our tasks. We have a lot to do with comments right now, but be sure that we have our hands on code.

**Comment by krzysztofspilka** [comment]
https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta5

**Comment by AMBudnik** [comment]
Bug confirmed in 0.16.0

**Comment by AMBudnik** [comment]
Fixed with 0.23.0 Updated demo: https://jsfiddle.net/452y4qsu/12/

Previously after scrolling comments appeared in random places, in 0.23.0 they're at correct positions.

**Comment by kvadd** [comment]
It looks like it's still an issue with alignment on horizontal scrolling for the comments though. Vertical scrolling seems to work fine.

**Comment by AMBudnik** [comment]
Hi @kvadd 
Can you guide me on how to replicate the issue for horizontal scroll? I've made an example https://jsfiddle.net/e83tbu7v/ where this behavior seems to be correct.

**Comment by kvadd** [comment]
@AMBudnik Thank you for an amazingly fast response! It looks like you actually have the issue on your jsfiddle you provided. It's subtle, since the table isn't very large. But on the last added comment (row: 9, col: 8) you can see it moves horizontally. Only by about 20 pixels. But, when you have 30 cells it's a much bigger issue. 

As you can see on the image below, from the example you provided, the comment should be after the I column.

![image](https://cloud.githubusercontent.com/assets/1159479/18265493/52fb30dc-7416-11e6-9a3d-5af0efc31103.png)

Please get back to me if you need any more information about the issue.

**Comment by AMBudnik** [comment]
thank you very much for the details and image @kvadd 
I'm reopening this issue.

**Comment by AMBudnik** [comment]
@kvadd 
I wasn't able to replicate the same bug with the newest version. Can you try it please: https://jsfiddle.net/oto23ejs/?

**Comment by kvadd** [comment]
The issue was when the table became too long. I have changed up your example and added a few more columns. It looks like it has been 'fixed', I think, however it looks like another issue has come out from this. 

If there two or more comments at the same row, they get switched out from time to time:
https://jsfiddle.net/oto23ejs/2/

![image](https://cloud.githubusercontent.com/assets/1159479/19183692/d74ebec8-8c79-11e6-82cd-228dc097301f.png)

**Comment by AMBudnik** [comment]
Thank you very much for your prompt reply Martin.
