### ISSUE TITLE
Comment Related Issue

### ISSUE THREAD

**Issue by iamrohitnigam** [handsontable/handsontable#2278]
Hi,

In extension to #2196.
Here is [jsFiddle](https://jsfiddle.net/iamrohit18/452y4qsu/5/) of code.

If we right click a row which has a comment and insert a row above. Then comment get transfer to the new generated row.

Please verify once.

Thanks

**Comment by AMBudnik** [comment]
I've reproduced it, thank you for reporting.

**Comment by KodjoSuprem** [comment]
I have the Same issue when using fixed rows (wich also add a scroll bar). In my opinion this is a HIGH priority bug.

**Comment by krzysztofspilka** [comment]
It's connected with #1823 which already addressed.

**Comment by krzysztofspilka** [comment]
@iamrohitnigam @KodjoSuprem @AMBudnik Could you confirm it's fxed (or not) in 0.23.0? Thanks

**Comment by AMBudnik** [comment]
@krzysztofspilka works well with 0.23.0, updated demo: https://jsfiddle.net/452y4qsu/11/

1. Use contextMenu to 'insert row' in 2nd row

previously comment stayed in 2nd row, now it's correctly moved to 3rd row.

**Comment by AMBudnik** [comment]
Mentioned #2196 issue is also solved in 0.23.0

**Comment by KodjoSuprem** [comment]
@iamrohitnigam still doesn't work on 0.26.1 check https://jsfiddle.net/6cgtyx3q/2/

Should I reopen an Issue?

**Comment by AMBudnik** [comment]
hi @KodjoSuprem 
I tried to `insert row above` on the 3rd row and it moves the comment down as intended.
Can you share more details about how can I duplicate the issue?

**Comment by KodjoSuprem** [comment]
@AMBudnik their is no row to insert. Can you check #3721 with the linked jsfiddle instead.
Thank you
