### ISSUE TITLE
IE9 Issue: Borders disappear when selecting multiple cells

### ISSUE THREAD

**Issue by geins** [handsontable/handsontable#2411]
Hello!
Using IE9 on Handsontable 0.14.1
when selecting whole column by clicking in the colheader, or by selecting multiple cells per drag-handle, the grey borders between cells disappear and also do not reappear when deselecting.

Due to intranet requirements I depend on IE9 :/
I know that 0.14.1 is not intended for IE9.

Thanks for your help!

**Comment by geins** [comment]
## You can see this effect on every example on the handsontable-homepage in IE9 and even IE9-Emulation:

### First do a selection. Notice the missing borders in the selection
![Multi-Cell-Selection:](https://cloud.githubusercontent.com/assets/5837776/7368087/117936b6-eda5-11e4-8128-4ab33bd73a37.png)

### Leave the focus. The borders are still lost
![After focus-out:](https://cloud.githubusercontent.com/assets/5837776/7368088/117f6f40-eda5-11e4-98d5-db951f77b01a.png)

# I came to the solution by myself:
Add following CSS-Rule:
```
.handsontable th,
.handsontable td {
  position: relative; /* Workaround for IE9 losing borders after multiselect */
}
```

**Comment by swistach** [comment]
Unfortunately @geins's solution isn't complete.

**Comment by swistach** [comment]
`background-clip` should be better than change in `position`

**Comment by AMBudnik** [comment]
Hi @geins 
We have released a new version 0.29.1 that should fix this issue. Can you confirm that?

**Comment by geins** [comment]
Hi @AMBudnik 
confirmed working on Win7 IE9.0.8112.16421

You're awesome people! Much appreciate your work.
Will still not get into production due to issue #3899, sticking with 0.28.4 atm.

Cheers, Ralf.

**Comment by AMBudnik** [comment]
Thanks for a quick confirmation @geins 
I hope that the second issue with `afterSetCellMeta` will be also fixed soon.
