### ISSUE TITLE
Use of column sorting causes unexpected rendering when the underlying data structure is modified

### ISSUE THREAD

**Issue by jiteshvassa** [handsontable/handsontable#2685]
Please see the following example:  http://jsfiddle.net/upf1b9yd/

This shows that the newly pushed item is automatically rendered.  if you comment out the "columnSorting" configuration, you will see that the pushed item does not get rendered.

The auto rendering behavior appears to be contrary to the documentation: http://docs.handsontable.com/0.16.1/tutorial-data-binding.html

The docs state: "Handsontable binds to your data source (array or object) by reference. Therefore, all the data entered in the grid will alter the original data source. In complex applications, you may have a purpose to change data source programmatically (outside of Handsontable). A changed being made will not be presented on the screen unless you refresh the grid on screen using the render method."

The auto rendering is causing issues for my use case where a number of events are coming through and arbitrary rendering causes performance issues.

**Comment by AMBudnik** [comment]
`Column Sorting` automatically enables `observeChanges` which triggers auto rendering of your instance. This subject will be discussed - if any changes, it will be updated.

**Comment by krzysztofspilka** [comment]
@jiteshvassa you're absolutely right, we should fix it. It is a task for at least a day or more because sorting plugin has already some tests written for validating whether observe.changes works fine in it and we need to detached them first and then write some new ones. I will add this to our Roadmap ideas for Q2 2016: https://trello.com/c/bU4FHywM/38-refactor-of-the-sorting-plugin

**Comment by AMBudnik** [comment]
The issue is still replicable in v0.35.0 http://jsfiddle.net/4z2h8q1o/

**Comment by AMBudnik** [comment]
Works the same in v `6.0.1.` data is being automatically rendered. Demo http://jsfiddle.net/handsoncode/843Lpsnv/

**Comment by aninde** [comment]
`columnSorting` will be fixed and it does not start `observeChanges`, which automatically render data. 

We are currently testing a version with many breaking changes,  I recommend observing information from issue [#5751](https://github.com/handsontable/handsontable/issues/5751).

**Demo**
version 8.0.0.rc http://jsfiddle.net/aninde/08xs2Lb1/

**Environment**
Handsontable version:8.0.0.rc
Browser Name and version: Google Chrome version 76.0.3809.100
Operating System: macOS Mojave 10.14.6

**Comment by aninde** [comment]
Still fixed by `8.0.0-beta1`.

@jiteshvassa we plan to release it around November 13 :)

**Demo:**
`8.0.0-beta1` - fixed http://jsfiddle.net/aninde/5ws9arxz/

**Comment by jiteshvassa** [comment]
Awesome, thank you!

**Comment by AMBudnik** [comment]
Hi @jiteshvassa 

now you can try our official 8.0.0-beta1 where the issue is solved http://jsfiddle.net/tem6x58w/

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```
`npm i handsontable@beta`

**Comment by krzysztofspilka** [comment]
@jiteshvassa  - @AMBudnik will keep you posted about the exact release date. It looks that we have some delay here.

**Comment by AMBudnik** [comment]
We just released `7.3.0` so now we can focus on the beta. We are planning to publish `beta2` soon.

**Comment by pnowak** [comment]
Still fixed by `8.0.0-beta.2-rev6`.

Demo:
8.0.0-beta.2-rev6 - http://jsfiddle.net/spz8ryc4/

**Comment by pnowak** [comment]
Still fixed by 8.0.0-beta2 - https://jsfiddle.net/e89cwkt2/

**Comment by aninde** [comment]
Updated demo with stable released v8.0.0 https://jsfiddle.net/aninde/f7tpy2dn/ still working well.
Even with commented `columnSorting` new rows are rendering. Closing as solved and released.

**Comment by AMBudnik** [comment]
Hi @jiteshvassa I hope that updating to version v 8.0.0 (stable) will fix the issue for you.

Feel free to share any feedback.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
