### ISSUE TITLE
Comments reposition while scrolling horizontally

### ISSUE THREAD

**Issue by itzikedar** [handsontable/handsontable#3081]
When table width is bigger then window width the table comment tool tip is in the wrong position.
Its seems the calculation referred only to the window width and not to table width.
Please note that table height and width was not set , Should be dynamic 

<img width="1090" alt="screen shot 2015-12-21 at 2 05 51 pm" src="https://cloud.githubusercontent.com/assets/4215737/11930406/b8f24e40-a7eb-11e5-93c5-dc2508ec4132.png">
<img width="1000" alt="screen shot 2015-12-21 at 2 06 09 pm" src="https://cloud.githubusercontent.com/assets/4215737/11930407/b8f37d24-a7eb-11e5-9697-8aa21f957b78.png">

**Comment by AMBudnik** [comment]
Confirmed, [Demo](http://jsfiddle.net/q4322b8v/)
Comments that are seen without scrolling are visible, but once that are hidden are gone.

**Comment by AMBudnik** [comment]
Still present in 0.27.0, demo: http://jsfiddle.net/8x70w8ts/

**Comment by AMBudnik** [comment]
Still present http://jsfiddle.net/dtpr8zfr/1/

**Comment by AMBudnik** [comment]
related: https://forum.handsontable.com/t/comment-positioning-wrong-when-hot-inside-any-scrolling-region/774

**Comment by jansiegel** [comment]
Should no longer be an issue after releasing `0.29.0`.

**Comment by AMBudnik** [comment]
Hi @itzikedar 
The issue should be finally fixed. Can you confirm that?

**Comment by itzikedar** [comment]
@AMBudnik working thanks for the quick fix

**Comment by AMBudnik** [comment]
Great :) It took nearly a year but know all issues related to comments should be fixed.
If you have any issues related to comments please do not hesitate to open a new ticket.

**Comment by apatton724** [comment]
Hi @AMBudnik  I am still seeing this issue.

I'm using  "version": "1.10.2",  (I found this in the package.json)

It is happening when the <body> of the document has a scroll bar. The comment boxes are much lower than the actual cell:  

![image](https://cloud.githubusercontent.com/assets/10131238/26412655/78aa0ee2-4077-11e7-8b2d-72721823d6f6.png)


I have 2 h.o.t. on one page. the first one is fine when scrolled all the way to the top. But the more I scroll down, the worst it gets.

Can someone give me some help? Thanks.

**Comment by AMBudnik** [comment]
Hi @apatton724 

I am not sure if it is not connected to the styling you're using. Do you use any CSS framework?
ps. I will appreciate any working demo to test it. Can you create one @apatton724 ?

**Comment by apatton724** [comment]
Hi @AMBudnik,

I am using Bootstrap. I will see if I can create an example. But let me know if you can think of why bootstrap would be an issue.

**Comment by AMBudnik** [comment]
Hi @apatton724 

I am just checking by to ask if you had time to investigate the issue?
We have been reported with few issues [related to Bootstrap styling](https://github.com/handsontable/handsontable/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20bootstrap)

**Comment by apatton724** [comment]
I have not. I will create a Gist and share it with you all.

Thank you for the followup.

Antoine

On Wed, May 31, 2017 at 7:11 AM, Aleksandra Budnik <notifications@github.com

**Comment by apatton724** [comment]
Okay , I've created 2 Gist. The first is 3 hot's wrapped inside of bootstrap wrappers; it works just fine because no scrolling is needed:
 - http://jsfiddle.net/4xzhqeg3/

The second gist has issues. You'll see that the very first comment works just fine, but any comment that you have to scroll down to get to will not display next to the cell it is for:
 - http://jsfiddle.net/4xzhqeg3/1/


Hope these examples help.

Thank you guys!
