### ISSUE TITLE
drop down not visible for the last row

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3210]
hello,
i have an handsontable with drop down list,
if i go to the last row , the drop down list is truncated.
regards
jm

http://jsfiddle.net/jeanmarc/81f0x1u6/
![dropdowntruncated](https://cloud.githubusercontent.com/assets/11042160/12944610/7d5aec00-cfe8-11e5-9ac1-1f812029feaa.png)

**Comment by AMBudnik** [comment]
Confirmed. Thanks for sharing @jeanmarc78

**Comment by krzysztofspilka** [comment]
@AMBudnik That's going to be a HUGE refactor of all editors. We'll start it next week and according to our roadmap it should be finished till the end of March.

**Comment by AMBudnik** [comment]
May have an impact on https://github.com/handsontable/handsontable/issues/2380

**Comment by krzysztofspilka** [comment]
From now on the dropdown will open to the top if there're too little space below it. This is just a workaround before we fully refactor the editors' code.

**Comment by Vinitha07ec** [comment]
But if the dropdown contains more values then we need to scroll the entire handsontable container to view the full options.Could you please work on this

**Comment by mariusk** [comment]
I'll just add another opinion on this. Using multiple handsontable instances on one page with autocomplete just isn't working. And it doesn't seem like something that is easily fixed by twiddling around z-index values in css files either. I haven't taken the time to figure out why, but I'm guessing there are hardcoded z-index values being set on dynamic elements like autocomplete tables. It's also painful on a more generic level, where table headers has a tendency to appear on top of other stuff. While I believe the latter may be solvable with documentation, I doubt the former can.

**Comment by AMBudnik** [comment]
@mariusk thanks for sharing. I created a new issue of your comment at https://github.com/handsontable/handsontable/issues/3443

**Comment by hgarciab** [comment]
Hello, I still have this issue due the fact that spaceBelow can be equal to spaceAbove on that scenario, the dropdown options are still unable to read, in this case handsontable should flip the dropdown up so the evaluation here should be `if (flipNeeded && spaceAbove >= spaceBelow)` instead of `(flipNeeded && spaceAbove > spaceBelow)`, here is the commit for the above suggestion change: [autocomplete flip upwards commit](https://github.com/handsontable/handsontable/commit/81f2cd7f86a8528aee133b3e53c78349ff6e4fc0#diff-b763e044fa12230ff192545f224b3b49R240)

e.g:

- with the current release  `if (flipNeeded && spaceAbove > spaceBelow)`
![image](https://cloud.githubusercontent.com/assets/1944242/15545168/9a6157c2-2258-11e6-9f01-e486be6cd541.png)

- implementing  `if (flipNeeded && spaceAbove >= spaceBelow)`
![image](https://cloud.githubusercontent.com/assets/1944242/15545264/f283cd90-2258-11e6-989b-7af9209a7c3b.png)

**Comment by AMBudnik** [comment]
@hgarciab could you share a demo where we will be able to replicate the issue?

ps. while I was testing this solution I came across this situation: http://jsbin.com/rojaroluqi/1/edit?js,output

I think that the dropdown menu should open above the cell not create an extra space on the page, but waiting for your opinion.

**Comment by hgarciab** [comment]
Sure @AMBudnik, here is the demo, hope this helps: https://jsfiddle.net/BeitaHere/6hf52e6x/7/, and yes I think would be better not use space that doesn't exists on the screen.

**Comment by AMBudnik** [comment]
thanks for sharing @hgarciab 
I'm reopening this issue. We have to test it more.

**Comment by AMBudnik** [comment]
after fixing this issue we should also check this one: https://github.com/handsontable/handsontable/issues/3443

**Comment by jaredbaszler** [comment]
I just ran into this issue today as we recently implemented a horizontal scroll bar on our HOT.  We only start with a single row and the main purpose is to let users add the x-amount of rows they need.  Which means the row they are working on is always at the bottom.  So this issue is compounded by that fact.  Please fix soon:

![image](https://cloud.githubusercontent.com/assets/9924084/20634485/31027216-b317-11e6-8d9d-aa01243757eb.png)

**Comment by AMBudnik** [comment]
Current topic for this issue: https://github.com/handsontable/handsontable/issues/3435
