### ISSUE TITLE
Cannot Navigate Past Hidden Column Using Keyboard if hot.updateSettings is Called in AfterSelection

### ISSUE THREAD

**Issue by gtiguy92** [handsontable/handsontable#3726]
See this [JSFiddle](http://jsfiddle.net/zagx9npp/). Select a cell in the currency column. Try to move left using the keyboard, you cannot. This seems to be caused by column 2 being hidden and by calling hot.updateSettings in the afterSelection callback.

**Comment by AMBudnik** [comment]
thanks for sharing @gtiguy92 
I got the same behavior (or the lack of it to be precise).

**Comment by gtiguy92** [comment]
Hi @AMBudnik,

Any update on a fix for this? We're using Handsontable as the core control for a complex project managements Angular2 application and it's working quite well!

Thanks,

@gtiguy92

**Comment by AMBudnik** [comment]
Hi @gtiguy92 
unfortunately there's no update yet but I think that we will have to wait for `updateSettings` refactor that we are planning to do in the end of this year (optimistic date, depends on future release bugs).

**Comment by gtiguy92** [comment]
Hi @AMBudnik,

Is there a specific GitHub Issue that represents the updateSettings refactor? I'll track that issue and stop bugging you :)

Thanks,

@gtiguy92

**Comment by AMBudnik** [comment]
There isn't any issue for a refactor. We will just take [all issues with label `updateSettings`](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Core%3A+update+settings%22+label%3A%22Type%3A+Bug%22) as will construct the code in a way that it will fix this list :-)

**Comment by wojciechczerniak** [comment]
@AMBudnik can't replicate in v8-beta2: https://jsfiddle.net/wnafydxk/
But it might have been fixed earlier

**Comment by AMBudnik** [comment]
It was still broken in http://jsfiddle.net/g7ucbd2w/ `7.4.2`, and `8.0.0-beta1` https://jsfiddle.net/tv5Lbo3j/. But it works in the latest beta2 http://jsfiddle.net/27vp3w0u/ (rev18). Great news!

**Comment by pnowak** [comment]
Hi @gtiguy92 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by pnowak** [comment]
Works well in 8.0.0-beta.2 - https://jsfiddle.net/qL46j13v/

**Comment by AMBudnik** [comment]
Morning @gtiguy92 !

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live. I highly encourage you to test the new version and leave some feedback. I hope the v8 will help you to improve your project.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
