### ISSUE TITLE
Scrolling page with mouse-wheel does not work when hovering a column-header

### ISSUE THREAD

**Issue by Sune1337** [handsontable/handsontable#4114]
### Description
When hovering a column-header, scrolling the page using the mouse-wheel does not work.

### Steps to reproduce
Create a Handsontable instance and specify width and height.
Hover a column-header and use the mouse-wheel to scroll the page.

### Demo
https://output.jsbin.com/zocegu/3

### Your environment
* Handsontable version: 0.31
* Browser Name and version: Chrome 56.0.2924.87
* Operating System: Windows 10 Home

**Comment by Sune1337** [comment]
If i don't specify width and height, scrolling the page works.
However a different issue arises then; the column headers get stuck on top of the page.

demo: https://jsbin.com/zocegu/4

**Comment by AMBudnik** [comment]
Hi @Sune1337 

Thanks for sharing. I've got the same result. When we keep the cursor on the column header page doesn't scroll.

**Comment by d-aven** [comment]
Hello!

> https://output.jsbin.com/zocegu/3

There is a different behaviour when I hold mouse on header:
1) On Windows scrolling just stucks
2) On MAC mouse wheel begins to control horizontal scroll

**Comment by AMBudnik** [comment]
Thank you for sharing your experience and tips @d-aven

**Comment by minteliuwm** [comment]
Hi, is this problem solved now?

**Comment by AMBudnik** [comment]
Hi @minteliuwm 

unfortunately, it is still present. I can replicate it with @d-aven demo and the latest `0.31.2` version.

**Comment by minteliuwm** [comment]
@AMBudnik I see, and can you tell me when this problem is solved ?

**Comment by AMBudnik** [comment]
Hi @minteliuwm 

We do not have a release date for this issue yet, however, I will mention it at our next team meeting.

**Comment by lulezi** [comment]
Hi @AMBudnik, do you have any news about the release date for this issue?

**Comment by AMBudnik** [comment]
Sorry but I do not have any news.  However, I can see that the same issue has been updated at https://github.com/handsontable/handsontable/issues/2560 and it's a part of our Backlog.

**Comment by wojciechczerniak** [comment]
Duplicate of #5212
