### ISSUE TITLE
Comments are always open on the right side of the cell even when there's no room for it

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4785]
### Description

Comments are always open on the right side of the cell even when there's no room for it. That is why they are not visible without scrolling the table and add extra space on the website.

### Steps to reproduce

1. Make the window narrow to fit the table
2. Mouse over a cell `G2`

**Result**:
The comment is opened on the left side of the cell.

![gif](https://user-images.githubusercontent.com/10757813/35962417-94ce5c2a-0cb1-11e8-85a2-d3e73975dab8.gif)

**Expected**: 
The comment is opened on the left side of the cell.

### Demo

http://jsfiddle.net/yd07qg6s/

### Your environment
* Handsontable version: 1.15.1./0.35.1
* Browser Name and version: Chrome 63
* Operating System: Windows 10

inform [forum](https://forum.handsontable.com/t/using-comments-with-stretchh-all/1789)

**Comment by small75** [comment]
In 1.18.1pro this problem exist too.
This issue is very important, especially for single-page applications, such as with ExtJS framework

**Comment by AMBudnik** [comment]
Thank you for checking and reporting that @small75 

We need to investigate this case.

**Comment by AMBudnik** [comment]
The issue is replicable in v `2.0.0.` and doesn't seem to work fine in any of the previous versions.

**Comment by ballawala-lv** [comment]
Hi I wanted to see if there was any update regarding this issue. Thank you!

**Comment by AMBudnik** [comment]
Sorry to say but we did not manage to schedule it yet

**Comment by InvinNO1** [comment]
Version 3 also being errors

**Comment by AMBudnik** [comment]
Works the same while using v 8.0.0 http://jsfiddle.net/AMBudnik/k8og17sm/

**Comment by aninde** [comment]
Fixed by v12.1.0 http://jsfiddle.net/xvsb1cj2/

**Comment by AMBudnik** [comment]
I'm closing this issue as the left comment is still partially cut on the edge so in this narrow viewport it works well.

Solved in version [12.1.0](https://handsontable.com/docs/release-notes/)

**Comment by Chandra-Adapa-wdc** [comment]
Hi @AMBudnik ,

I still see this issue in 12.1.2 of handsontable, can you please confirm which version handsontable we need to choose to resolve the issue ?

**Comment by AMBudnik** [comment]
Hi @Chandra-Adapa-wdc 

Can you share an example where the issue is replicable?

I tested the newest version (the issue is solved from v12.1.0) v14.1.0, and for that particular case, the comment position is still correct.


![Zrzut ekranu 2024-02-8 o 09 20 49](https://github.com/handsontable/handsontable/assets/10757813/ee5d6f19-d086-442e-97c0-a8d4950df3d6)

**Comment by Chandra-Adapa-wdc** [comment]
Hi @AMBudnik ,

I still able to replicate this with stretchH: All, I see most of your demos which you mentioned its working, this option is removed.

Thanks,
chandra

**Comment by AMBudnik** [comment]
Hi @Chandra-Adapa-wdc 

Could you please contact us at support@handsontable.com and share implementation details and your OS/Browser details?

I was using this demo, https://jsfiddle.net/c2um3nqv/, on Chrome 130 and macOS Ventura, and besides a slight misalignment when I resize a window, I do not see comments displayed incorrectly. 

![comments](https://github.com/user-attachments/assets/55bd480b-fc03-422b-8cb8-b3dff3a30c25)
