### ISSUE TITLE
collapseAll method for collapsibleColumns doesn't work with sorting enabled (observeChanges)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4999]
### Description

reported at [forum](https://forum.handsontable.com/t/collapsiblecolumns-collapseall-conflict-with-columnsorting/1947)

If we add `columnSorting: true` to instance settings (on initialization or via `updateSettings`) we are not able to collapse headers programmatically via `collapseAll` method.

### Steps to reproduce

1. Check the column headers. You get `+` sign but columns are visible, not collapsed.

![image](https://user-images.githubusercontent.com/10757813/38408711-03dc1f68-397f-11e8-879e-e85263a784f3.png)

### Demo

https://jsfiddle.net/tq81x81n/ (with `collapsibleColumns: true` from Client
https://jsfiddle.net/handsoncode/8j2kzjwd/ (with `collapsibleColumns` defined)

### Your environment
* Handsontable version: 1.18.1
_It looks like it has been working like this since it has been added in v `1.10.1`_
* Browser Name and version: Chrome 65
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Still works the same in v`6.0.1`

**Comment by wojciechczerniak** [comment]
Disabling `observeChanges` plugin solves the issue: https://jsfiddle.net/7kosr5yx/
Will be fixed by #5945

**Comment by AMBudnik** [comment]
Fixed with `8.0.0.-rc1`

Updated demo https://jsfiddle.net/handsoncode/tr3u7h5L/
![image](https://user-images.githubusercontent.com/10757813/65246346-a3ff4d00-daee-11e9-8e86-5602aeb9a07b.png)

**Comment by AMBudnik** [comment]
Fixed for the official beta 8.0.0-beta1 as well https://jsfiddle.net/nagced8r/

**Comment by pnowak** [comment]
7.4.2 https://jsfiddle.net/uk1gj8p7/ (broken)
8.0.0.-beta1 https://jsfiddle.net/13sjcL95/1/ (**issue solved**)
8.0.0.-beta2-rev2 https://jsfiddle.net/8tjr9suL/2/ (**issue is still resolved**)

<img width="241" alt="Zrzut ekranu 2020-05-8 o 12 04 24" src="https://user-images.githubusercontent.com/1555809/81395541-1d9e8680-9124-11ea-9f8c-6a2202eb9832.png">

**Comment by AMBudnik** [comment]
The issue is officially solved in v 8.0.0. https://jsfiddle.net/avcgw4dm/
