### ISSUE TITLE
Cannot read property 'classList' of null.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5128]
### Description
When the second time I try to edit the cell - after scrolling outside the viewport - there is an error
`Uncaught TypeError: Cannot read property 'classList' of null`.
The error occurred only at `allowInvalid: false`.

### Steps to reproduce
![may-30-2018 08-33-06](https://user-images.githubusercontent.com/1555809/40703009-27aa8080-63e4-11e8-9f76-c041d3abc55e.gif)

### Demo
http://jsfiddle.net/p1u7yhp4/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
Looks like duplicate of #5119.

**Comment by AMBudnik** [comment]
fixed with this one https://github.com/handsontable/handsontable/issues/5119

**Comment by adamdehaven** [comment]
@AMBudnik I'd like to report this issue is still/again present in version `7.1.0`

I currently don't have a valid JSFiddle to share (as my code is too deep at this point to split off a relevant demo) but if I remove the `allowInvalid` from the dropdown column, the error does not appear.

**Comment by AMBudnik** [comment]
@adamdehaven 
here's version 7.1.0 and it doesn't return an error in the console http://jsfiddle.net/n8z7L0eh/ (Tried with Win 10 / Chrome 75)
