### ISSUE TITLE
EcoRenderers feature

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#5769]
### Description

This issue is about implementing a new feature internally called as `EcoRenderers`. The idea of this is to increasing Handsontable performance by re-rendering cells only when their value has changed. I assume that after implementing this feature issues related to scroll performance or refresh table lag after cell edit should disappear (or at least less annoying).

This feature is currently in the early development stage (researching and prototyping). Any important changes or news will be updated in this post.

**Comment by aaronbeall** [comment]
This is of great interest to me!

Also please keep in mind cell dependencies. I really like how MobX and similar libraries [automatically track dependencies by access](https://mobx.js.org/best/react.html), it would be amazing if calling `getSourceData()` and such from a renderer would track the dependency, so that for example a triggered re-render of one cell would also re-render any renderers that had called `getSourceData()` on that cell. We make heavy use of renderers that have computed rendering (diffs, totals, conditional formatting).

**Comment by tsohr** [comment]
+1. holymoly, Can't wait for this.

**Comment by AMBudnik** [comment]
Inform [`forum`](https://forum.handsontable.com/t/handsontable-causing-performance-issue/2983)

**Comment by rayokao** [comment]
I have noticed that Handsontable internally **reads** plenty from a DOM-property called _offsetWidth_ (and _offsetHeight_). Oddly, **reading** this property forces browser to reflow. This issue is known to cause rendering issues, jerky scrolling for example. The issue is explained [in this Sitepoint article](https://www.sitepoint.com/10-ways-minimize-reflows-improve-performance/). According to my own profiling efforts I would say that the way the grid dimensions are calculated is the issue, not the renderers.

**Comment by tkane2000** [comment]
Hi @budnix!  

We're having major problems with scroll performance, so thanks for addressing the issue!

It sounds like the ecoRenderer solution is for tables in which the viewportColumnRenderingOffset and viewportRowRenderingOffset are set to the full length of columns and rows(?).  We have large tables (100 x 50,000) so we're setting both to auto and table cells will be rendered as you scroll.

Am I correct that this won't help in that scenario or am I missing something?

Thanks!

CC @AMBudnik

**Comment by budnix** [comment]
@tkane2000 Generally after implementing the new algorithm scrolling performance should be less annoying. No matter what the `viewport{Row|Column}RenderingOffset` option value was set. Although in the new approach hidden columns are still rendered in the DOM they are not touched any more after the cell is edited or scrolled. The first observation after experimenting with it is that the more complicated cell renderers are, the better the performance while scrolling gets.

@rayokao Thanks for tips! Unfortunately implementing that algorithm with some refactoring is so time-consuming. Investigating the code for fixing all tips included in the link should be done in a separate project.

Currently, the project is still in an early stage of development so there is no build available to check.

**Comment by tkane2000** [comment]
@rayokao It looks like those offset{Width|Height} start with a call to the render method, so reducing renders should help.  Fixing the issues with reflows could hurt if there's a better solution.
@budnix @AMBudnik Here's an old tkt for that: #3370.  Is it possible to have it addressed as well?

![image](https://user-images.githubusercontent.com/372544/53989960-27c68e80-40f5-11e9-870f-170a6c86d083.png)
handsontable.full.js: Line 46973:  ```fillWidth = dummyElement.offsetWidth;```

**Comment by AMBudnik** [comment]
Hey @tkane2000 
#3370 a bit different subject. It won't be addressed in the first Stage of the performance update and especially not in the eco-renderers.
I hope that once we push some commits it would be clear what this is for, but thanks for mentioning. We'd need to create an epic for Stage 2 so all ideas are welcomed 👍

**Comment by GaelPaquet** [comment]
Hi @budnix, how do you progress on these extremely important eco renderers ? How will this work ? Thanks

**Comment by budnix** [comment]
Thanks for asking. The project is still under heavy development. It took some time since the last comment and I can say that we currently fix all issues found while manual testing and automatic tests (there are a lot of them).  Right now I can share some demos which can be compared to how scroll and editing performance is changed when renderers used in the Handsontable are very demanding.

EcoRenderers: https://jsfiddle.net/budnix/xptfvyza/
7.0.2 version: https://jsfiddle.net/budnix/sLzt267n/

I don't count my chickens before they hatch that's why I can not promise how the performance will change in the end.

**Comment by GaelPaquet** [comment]
Thanks Krzysztof for the prompt answer. Looks really promising ! Great job !

**Comment by KhogaEslam** [comment]
Hello, that's a great boost in performance
specially in my case i have a large number of merged cells [up to 200]
and the performance increased so much
try this:
with merged cells>
EcoRenderers:  https://jsfiddle.net/khogaeslam/8vgxbtac/2/
7.0.2 version: https://handsontable-try.netlify.com/

**Comment by AMBudnik** [comment]
Hey @aaronbeall @KhogaEslam @GaelPaquet @tkane2000 @rayokao @tsohr I'm happy to announce that this issue got officially solved in patch `7.1.1`.
Thank you for the feedback :)

**Comment by vmagalhaes** [comment]
@AMBudnik in the patch 7.1.1 the eco-renderer is working?

**Comment by AMBudnik** [comment]
Hey @vmagalhaes only the 1 Stage is done.
Next one is the cell meta refactor (starting next week)

**Comment by vmagalhaes** [comment]
I'm having trouble with patch 7.1.1, the scrolling is bad. Make a look:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14242447/66832832-0fdba680-ef31-11e9-9978-a1771337d7e5.gif)

I'm using Angular, the Angular Material have this virtual scrolling:
https://material.angular.io/cdk/scrolling/overview

Have some way to apply this? It is very good.
Or have some way that I can apply to make this scrolling better?

Regards.

**Comment by AMBudnik** [comment]
Please share the example with me on emails @vmagalhaes (mine is support@handsontable.com)

**Comment by vmagalhaes** [comment]
@AMBudnik Example: https://jsfiddle.net/41odmnse/

**Comment by wojciechczerniak** [comment]
@vmagalhaes Handsontable already has virtual scrolling. There is no need for Angular Material.

Your example has a very time consuming `for` loop in the renderer. Please contact support@handsontable.com or create an issue and describe your use case so we can help you find the best solution.

Let's keep this thread about eco renderers only.

**Comment by pinuchfab** [comment]
Hello, I m using v 6.2.2,
I have advise we should upgrade but I want to make sure we use the EcoRender feature.
Has EcoRender been officially released?
Which version would you recommend?
Regards

**Comment by wojciechczerniak** [comment]
Hi @pinuchfab,

It's not released yet. We're currently refactoring huge parts of the code to make this possible.

Cheers

**Comment by hugh-barclay** [comment]
Hi,

We are using v 6.2.2 also. 

We have been waiting for decent performance improvements before upgrading.

Is there an estimated ETA when this feature will be released?

**Comment by AMBudnik** [comment]
Hi @hugh-barclay 

this project is so complex that it is described by a couple of issues. Currently, we're here https://github.com/handsontable/handsontable/issues/6233 doing a code review.

**Comment by underfisk** [comment]
@AMBudnik I would like to say a few things as advice for this Eco render feature. In React we usually work with JSX and we are forced to create elements outside react virtual dom and by doing that we lose the reconciliation process and have to rely on HoT which isn't doing anything regarding it.
Shallow comparison for values is good but components reference may be mutated or changed, my concern using HoT in production is that 
Using redux with a few hundreds of that somethings create a bunch of unnecessary re-renders due to the fact that components converted down to childs of the HoT td will always be re-created and now simply updated, this has been a huge issue

**Comment by pinuchfab** [comment]
Hello
I have been evaluating the beta, we had a couple of small problems which I fixed myself but will report them when I got more time with the proposed fixes.
There is one particular issue that I don't understand and need help. Can you confirm that undo redo works for row insert? For instance add a row then undo, I expect the row to be removed, well it did in previous version but not in this beta.
Regards,
Fabien

**Comment by AMBudnik** [comment]
I'm glad to hear some feedback on beta version @pinuchfab 
Please send me an email to support@handsontable.com when you're ready

**Comment by dtomaszewski** [comment]
@AMBudnik is there an approximate date when this feature is released ?

**Comment by AMBudnik** [comment]
@dtomaszewski we needed all the hands on the desk to release version 8 (we're planning a code freeze next week) so we needed to pause this subject. However, we plan to get back to it soon.

**Comment by ElixirMike** [comment]
Curious based on @underfisk  comments, will this optimization work if we're using the react wrapper?

**Comment by underfisk** [comment]
@ElixirMike I don't think so because the problem on using React with Handsontable is reacting virtual dom works, Handsontable does not support very well redux and the result is its performance, in my experience if you edit something and dispatch a redux action the editor freezes until the action finishes which is not good at all (will enforce the re-creation of the whole DOM)

**Comment by ElixirMike** [comment]
@underfisk hmm,  we don't use redux however, would that make a difference? I guess we'll just test it out when it's delivered

**Comment by underfisk** [comment]
@ElixirMike The issue is related to Immutability support and not redux itself

**Comment by jeremy-smith-maco** [comment]
Now that v8 is released, is this feature going to be considered to continue implementation on?

**Comment by underfisk** [comment]
@jeremy-smith-maco I still have the same question since they closed my topic. V8 didn't solve anything related to React, problems still persist and their wrapper doesn't have any kind of memoization optimization. I would really like to see a real support for React,  the problem is also on the wrapper itself 
With v8 i got a bug that when handsontable is Destroyed it should unmount the component but simply stands in there triggering the lifecycle lol

**Comment by AMBudnik** [comment]
Hi @jeremy-smith-maco @underfisk we've just released the version which allowed our team to take a deep breath and relax, so around half of the team is on the vacation. When they are back we'll be able to work on the Roadmap for upcoming months. I will let you both know about any updates on the Roadmap.

**Comment by underfisk** [comment]
@AMBudnik So far v8 did nothing for React, the table still the same and in our use case some parts seem even worse

**Comment by AMBudnik** [comment]
> some parts seem even worse

can you email me with a demo or open a new topic, @underfisk? 

Ecorenderers are not a part of the v8.0.0 list https://handsontable.com/docs/8.0.0/tutorial-release-notes.html
We've made some changes to the cellmeta operability but those issues should not be considered as the 'fix for renderers'.

**Comment by underfisk** [comment]
@AMBudnik Not talking about renderers, we have a Financial table that works with some parts like hidden rows/columns and some of that seems quite worse, I would need to investigate but the upgrade did not help at all

**Comment by AMBudnik** [comment]
> I would need to investigate

Please do. I'm open to investigating any demo you can send.

**Comment by underfisk** [comment]
@AMBudnik I don't use popularFromArray and now each time i delete a row it throws the following: Error: populateFromArray parameter `input` must be an array of arrays
Plus if I re-render the table, it destroys internally (the flag is set to true) but the wrapper does not unmount so it continues its lifecycles even though handsontable is destroyed

**Comment by pinuchfab** [comment]
I was using the 8.0 beta1 and it was working fine.
Then today I tried to use the release, and experienced some problems.
We are reverting to the beta1 version in the meantime.
I will try again later and gather some feedback.

**Comment by AMBudnik** [comment]
@pinuchfab please share the demo with me on support@handsontable.com

**Comment by hugh-barclay** [comment]
> Hi @jeremy-smith-maco @underfisk we've just released the version which allowed our team to take a deep breath and relax, so around half of the team is on the vacation. When they are back we'll be able to work on the Roadmap for upcoming months. I will let you both know about any updates on the Roadmap.

Any news regarding the roadmap?

**Comment by AMBudnik** [comment]
Hi @hugh-barclay Eco-renderers are on our Roadmap but the Roadmap hasn't been precisely described by dates yet.

**Comment by haraleib** [comment]
Is there some new information about EcoRenderers? Relating to this I only see https://github.com/handsontable/handsontable/issues/5762 for cancelling rerendering the whole table on single cell change. Am I missing something out here?

**Comment by AMBudnik** [comment]
@haraleib, not a lot changed from my last comment. Eco-renderers are still on the Roadmap.
What has been added (to allow developers to render flexibility) is an ability to suspend rendering (further described here https://handsontable.com/docs/8.3.2/tutorial-suspend-rendering.html).
However, the part of a single cell rerender hasn't been added yet.

**Comment by haraleib** [comment]
I tried something like this, but I didn't get the desired performance results. Is it possible do use batch function inside a hook?
```
 hot.addHook('afterValidate', function (isValid, value, row, col) {
             if(conditionMet){                   
                 hot.batch(() => {
                 hot.setDataAtCell(1, 1, 'x');
                 hot.setDataAtCell(1, 2, 'y');
                 hot.setDataAtCell(1, 3, 'z');
                });
             }
});
```

**Comment by AMBudnik** [comment]
@haraleib The `afterSetDataAtCell` hook is called on the execution of `setDataAtCell` so in the following case you end up with an infinite loop.

**Comment by haraleib** [comment]
@AMBudnik It depents on the condition. F.e.: A condition could be `if(col === 0 && row === 0){...}` to avoid an infinite loop.
Nevertheless I was not able to make any performance results. Is it possible to batch like this inside a hook ? If so, I have to check my code.

**Comment by AMBudnik** [comment]
Yes @haraleib you can use batch within a hook. Here https://jsfiddle.net/handsoncode/q2vgx5y1/ is a demo that I've converted that you can test

**Comment by krishamatya** [comment]
I am still facing this issue. I have 100 record in handsontable, and when i update one cell, the cell render of whole table cells gets called in CustomRenderer. this is disaster from the performance point of view

**Comment by julioxavierr** [comment]
+1

**Comment by m-towery** [comment]
+1

**Comment by 19Qingfeng** [comment]
+1

**Comment by 19Qingfeng** [comment]
When I change a cell,The custom rendering of pictures will reload.

**Comment by dheerajpateria** [comment]
Is there any update of this Feature

**Comment by adrianszymanski89** [comment]
Hi @dheerajpateria 

Not yet. However, with each release, we are making some improvements in general performance. We will update this issue once it's done.

**Comment by SamyakMeshram** [comment]
Is there any update on the release of this feature

**Comment by ElixirMike** [comment]
also interested in update in regards to timing

**Comment by AMBudnik** [comment]
Hi, @ElixirMike @SamyakMeshram, we will also make sure to notify you when it is fixed. Now, no pull requests are attached.

**Comment by SamyakMeshram** [comment]
Can you please provide a work around so that we can restrict the over rendering of the table.As per our usecase a large memory leak is taking place in the tool.

**Comment by AMBudnik** [comment]
Hi @SamyakMeshram the ecorendering process is a completely new approach. There are no obvious workarounds here.
However, if you experience any performance issues please feel free to share more details with me via support@handsontable.com

**Comment by sl01k** [comment]
We're moving feature requests to our community forum where they can be properly tracked and voted on by the community.

This topic already has a thread here: [GH-5769: Is there a way to make faster appending new data to already loaded data?](https://forum.handsontable.com/t/gh-5769-is-there-a-way-to-make-faster-appending-new-data-to-already-loaded-data/4516)

Closing this issue. Feel free to continue the discussion on the forum.

Thank you!
