### ISSUE TITLE
Sorting after filtering with minSpareRows set

### ISSUE THREAD

**Issue by sandeepdarga** [handsontable/handsontable#5983]
### Description
There seems to be an issue with sorting after filtering if minSpareRows is true or set to a number.

For example, if the setting is minSpareRows: 1, then when you filter, then sort, the sort seems to be off by one rows. If its minSpareRows: 3, then the sort is off by 3 row.

### Steps to reproduce

1. Filter using the button I've added to the bottom of the table. (uses the Filtering API, it also breaks if you manually filter anything)
2. Sort descending the "A" column, and you can see how the sorting is off by however many extra blank rows you want added. See below in the image how the A column should be descending, but the bottom three rows are out of order (minSpareRows: 1).

### Demo
https://jsfiddle.net/3b7qw456/

### environment
* Handsontable version: 7.0.2
* Browser Name and version: Chrome, Version 73.0.3683.103 (Official Build) (64-bit)
* Operating System: Windows 8

**Comment by AMBudnik** [comment]
Hey @sandeepdarga 

there is an issue where our developers describe that the sorting and filtering do not work together well https://github.com/handsontable/handsontable/issues/5890

but your issue and the one that he mentioned should be fixed after releasing this change https://github.com/handsontable/handsontable/issues/5112

**Comment by aninde** [comment]
Sadly bug is still present in the latest and oldest version of `8.0.0-rc1`. I wasn't expected that. @AMBudnik could you double-check that?

**Demo**
v. `8.0.0-rc1` (25.09.19) https://jsfiddle.net/aninde/3ek74rx0/ 

**Environment**
Browser Name and version: Google Chrome version 76.0.3809.100
Operating System: macOS Mojave 10.14.6

**Comment by AMBudnik** [comment]
True, still `columnSorting` does not work, even when the indicator is shown.
The `afterColumnSort` shows results as the data was sorted so it may be a matter of reloading the data.

**Comment by wojciechczerniak** [comment]
Works for me with todays build: https://jsfiddle.net/835dh0qx/

Can you verify @aninde @AMBudnik ?

**Comment by AMBudnik** [comment]
I wouldn't call it fixed.

If we click the button sorting works, but
* last row 'Ford' does not take part in sorting
* should/n't we see a spare row?

![bug](https://user-images.githubusercontent.com/10757813/65757145-d7f1f800-e116-11e9-8865-7957faea5514.gif)

**Comment by wojciechczerniak** [comment]
I see. And I think I know why. Column sorting subtracts `minSpareRows` from the `rowCount`.

You're right, we should see a spare row here.

**Comment by AMBudnik** [comment]
This issue is still replicable using v 8.0.0 https://jsfiddle.net/q6ho2gLt/

**Comment by demtario** [comment]
Thanks for the report, the issue was fixed in #13366 and will be a part of the next release.
