### ISSUE TITLE
Wrong cell meta removed when deleting rows

### ISSUE THREAD

**Issue by ottosson** [handsontable/handsontable#6051]
### Description
I'm removing rows using alter("remove_row") with an array of ranges. Second time I use remove_rows it's not removing the corresponding metadata for the rows I provided. See Stackblitz example.

### Demo
https://stackblitz.com/edit/handsontable-angular-8y68hu?file=app/app.component.ts

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome 74
* Operating System: Windows 10

**Comment by ottosson** [comment]
Having a grid with 10 rows and setting cell metadata on first cell in each row to x0-x9 and then running remove_row two separate times, giving it index ranges [0, 1] and [0, 2] will result in x2-x8 remaining.

Running remove_row one time giving it [[0, 1], [0, 2]] will result in x1-x8 remaining.

Something feels weird here.

**Comment by AMBudnik** [comment]
Hey @ottosson 

this issue should get fixed after adding the mapper https://github.com/handsontable/handsontable/issues/5112

**Comment by ottosson** [comment]
That's great! Any ETA when this will be released?
Thanks!

**Comment by AMBudnik** [comment]
It's a work in progress so it is really hard to tell.
The best way to track the changes is by checking this part 

![Zrzut ekranu 2019-06-14 o 10 43 28](https://user-images.githubusercontent.com/10757813/59496247-54770880-8e91-11e9-8e72-93963be1cd4f.png)

**Comment by deeperzone** [comment]
Have a same problem. I use cell metadata to define classes. After i remove row, metadata shifting.

**Comment by deeperzone** [comment]
I'm override default ContextMenu **remove_row**, with my callback function => onRemoveRow.
The main idea is to delete one line by alter('remove_row').

```
  onRemoveRow(selections: Selection[]) {
    if (!selections || selections.length === 0) {
      return;
    }

    let counter = 0;
    for (let selectionIndex = 0; selectionIndex < selections.length; selectionIndex++) {
      const selection = <any>selections[selectionIndex];
      for (let rowIndex = selection.start.row; rowIndex < selection.end.row + 1; rowIndex++) {
        this.instance.alter('remove_row', rowIndex - counter++);
      }
    }
  }
```

**Comment by AMBudnik** [comment]
Get @ottosson we've just released a branch that provides changes that may help you to achieve the goal. https://github.com/handsontable/handsontable/tree/feature/issue-5751

**Comment by ottosson** [comment]
This is still an issue as of 8.0.0-beta.1

I understand this to be work in progress, but can I expect this issue to be fixed with of the 8.0.0 release?

**Comment by AMBudnik** [comment]
Here's the cell-meta update https://github.com/handsontable/handsontable/pull/6254 @ottosson 
however, it might not be the fix yet. The reason for doing those changes was to prepare cell meta or other stages of rendering improvements (@budnix prepared a good description within the topic).

**Comment by ottosson** [comment]
Thanks! So it's not really sure it's coming in 8 then?

**Comment by AMBudnik** [comment]
We'll be doing beta2 soon (or planning to do). The cell-meta makes us part the task into a couple of PRs and some of them are part of beta1, some will be beta2. It may sound a bit complicated but we prefer doing small steps to get this done than pushing 8.0.0 stable with untested solutions. We're not able to tell how many betas will be pushed before we'll publish stable 8.0.0.

**Comment by ottosson** [comment]
Sounds reasonable. Metadata is a showstopper for me and I'm on the verge of writing an ad-hoc metadata solution until it has been resolved in HoT and was just curious if it was worth to do it or wait for the release.

**Comment by aninde** [comment]
As @AMBudnik wrote, we are currently working on a new beta version of 8.0.0. At this stage, we test created solutions.
Sadly current version of new [cell-meta](https://github.com/handsontable/handsontable/pull/6254)  does not fix described here issue. The result is the same as it was.
![Screenshot 2019-12-16 at 14 53 38](https://user-images.githubusercontent.com/30186818/70912269-e06e1680-2013-11ea-8c77-3c6c82da9812.png)

Demo https://stackblitz.com/edit/handsontable-angular-vczjnk?file=app/app.component.ts

**Comment by aninde** [comment]
I was wrong, according to @budnix we should also change a version of `handsontable/angular` in above [comment](https://github.com/handsontable/handsontable/issues/6051#issuecomment-566071007) to test if this really is fixed. 
Supposedly creating a custom `handsontable/angular` version of PR is a more complicated process than I thought and requires devoting time to the developer.

**Comment by aninde** [comment]
@budnix tested described here issue locally and like he said on [comment](https://github.com/handsontable/handsontable/pull/6254#issuecomment-566491490) for PR:

> @aninde I've checked the issue #6051 with these changes, and cell meta is removed correctly. Unfortunately, version 8.0.0 is not compatible with the angular wrapper and cannot be used yet.

IMHO we should add a proper demo to present the correct working and to close this issue after release the next beta of 8.0.0 however, I need help with that like I mentioned [above](https://github.com/handsontable/handsontable/issues/6051#issuecomment-566498162).
We should also add tests so that error does not recur in the future.

**Comment by AMBudnik** [comment]
Result remains the same in 8.0.0-beta2-rev14 https://stackblitz.com/edit/handsontable-angular-vmbt4p?file=app/app.component.ts

![Zrzut ekranu 2020-06-16 o 11 37 31](https://user-images.githubusercontent.com/10757813/84758467-c9f64700-afc5-11ea-8c20-08a39ca5abb7.png)

**Comment by wojciechczerniak** [comment]
@AMBudnik @aninde I've recreated the example in vanilla JS. Please check if I did it correctly

Broken in 7.4.2: https://jsfiddle.net/za0tr7bq/1/
Fixed in v8-rev21: https://jsfiddle.net/za0tr7bq/

**Comment by aninde** [comment]
@wojciechczerniak thank you for demo. It's fixed also on the latest `8.0.0-beta2-rev22` https://jsfiddle.net/aninde/v32pdxkb/, so it should probably be fixed on our release candidate for 8.0.0-beta2.

**Comment by AMBudnik** [comment]
Hi @ottosson 

I have good news! We've just released 8.0.0-beta2 that should fix the following issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. I hope it solved the issue for good. 
Thank you for your input.

**Comment by ottosson** [comment]
That's excellent news @AMBudnik, thanks a lot. Now I just want the Angular wrapper to get updated as well and I'm all satisfied! =)

**Comment by AMBudnik** [comment]
Hi @ottosson yesterday we've released new Handsontable ([8.0.0](https://github.com/handsontable/handsontable/releases/tag/8.0.0)) and Angular version ([6.0.1](https://github.com/handsontable/angular-handsontable/releases/tag/6.0.1)). I'd be happy to get some feedback from you :)
