### ISSUE TITLE
[7.1.1] Error when columnSummary plugin tries to create a row

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6300]
### Description
There is an error in console when `columnSummary` tries to create a row with calculations.
This error appears since `8.0.0-rc1`. http://jsfiddle.net/aninde/h32ktve4/

The error doesn't appear when the row in which the calculation is to be made is rendered.

In v. `7.1.1.` in the same reproduction, there is a different error, but at least rows are rendering.  `columnSummary` creates two rows with calculation, which is described in #5794

**Actual result**

v. `8.0.0-rc1`
![Screenshot 2019-09-30 at 13 37 35](https://user-images.githubusercontent.com/30186818/65875459-9c119980-e387-11e9-915f-4b4e80898d7c.png)

![Screenshot 2019-09-30 at 10 57 42](https://user-images.githubusercontent.com/30186818/65875047-f52cfd80-e386-11e9-94a6-1a5849beb64c.png)

v. `7.1.1` - double row, described [here](https://github.com/handsontable/handsontable/issues/5794) 
![Screenshot 2019-09-30 at 13 37 24](https://user-images.githubusercontent.com/30186818/65875597-e4c95280-e387-11e9-8d85-6678417fce07.png)

**Expected result**
`columnSummary` should create one row with calculations. 
![Screenshot 2019-09-30 at 13 47 49](https://user-images.githubusercontent.com/30186818/65876206-06770980-e389-11e9-8209-758a57ed5693.png)

### Demo
Works, but creates improper additional row v. `7.1.1.` http://jsfiddle.net/aninde/za3w2sn4/
Bug v. `8.0.0-rc1` http://jsfiddle.net/aninde/h32ktve4/

### Your environment
* Handsontable version: `8.0.0-rc1`
* Browser Name and version: any
* Operating System: any

**Comment by wszymanski** [comment]
It should be fixed:

https://cdn.jsdelivr.net/gh/handsontable/handsontable@ad2e44e07bde789ca11ab1b3eaf021498d54279b/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@ad2e44e07bde789ca11ab1b3eaf021498d54279b/dist/handsontable.full.css

**Comment by aninde** [comment]
@wszymanski in latest v. of `8.0.0-rc1` a bug is still replicable. 
There is a warning in console and row doesn't rendering. 
Warning occurs when `columnSummary` tries to create a row, which doesn't exist.  Maybe it's planned action, by design. @wszymanski, @wojciechczerniak WDYT?


![Screenshot 2019-10-08 at 08 33 42](https://user-images.githubusercontent.com/30186818/66372506-6df31180-e9a6-11e9-92a8-199f455ffe72.png)


Demo: 
[latest](https://github.com/handsontable/handsontable/issues/6300#issuecomment-539062518) v. `8.0.0-rc1` http://jsfiddle.net/aninde/cj9d3ae8/

**Comment by wojciechczerniak** [comment]
@aninde If there's a warning it's by design. The developer should fix the Handsontable config.

**Comment by aninde** [comment]
Ok, so the issue is fixed. There is no error in the console, only warning. 
A warning that leads the developer to leave a spare line for the calculation result.
That can be done by enabling [minSpareRow](https://handsontable.com/docs/7.1.1/Options.html#minSpareRows) or by adding an empty object to dataSource.

**Comment by aninde** [comment]
With improper use, without spare row there is error in console when data is change with `alter` + `columnSummary` in `8.0.0-rc1`.

**Demo**
with a error `8.0.0-rc1` https://jsfiddle.net/aninde/j9vmha5n/

**Comment by wszymanski** [comment]
> With improper use, without spare row, there is error in console when data is change with `alter` + `columnSummary` in `8.0.0-rc1`.
> 
> **Demo**
> with a error `8.0.0-rc1` https://jsfiddle.net/aninde/j9vmha5n/

Please check that:

https://cdn.jsdelivr.net/gh/handsontable/handsontable@b364760caee51c4b3ac30af4653a53d69dbd889a/dist/handsontable.full.js
https://cdn.jsdelivr.net/gh/handsontable/handsontable@b364760caee51c4b3ac30af4653a53d69dbd889a/dist/handsontable.full.css

**Comment by AMBudnik** [comment]
@wszymanski you're sample on Windows https://jsfiddle.net/handsoncode/jg7c29oe/

looks like this

![image](https://user-images.githubusercontent.com/10757813/66836183-30bbf000-ef61-11e9-9bf2-a694efa0cda5.png)

* no error in the console only the `handsontable.full.js:7361 One of the Column Summary plugins' destination points you provided is beyond the table boundaries!` warning, 
* `minSpareRows` works well

**Comment by aninde** [comment]
@wszymanski like AMBudnik said, it works well on [new](https://github.com/handsontable/handsontable/issues/6300#issuecomment-541784683) build of `8.0.0-rc1`.

It works when:
- result of `columnSummary` is removed by `alter`

**Comment by AMBudnik** [comment]
Issue solved in v 8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
