### ISSUE TITLE
If the table fits well within the viewport, border line is not drawn on an edge of an overlay

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6392]
### Description

When the Handsontable root container has a specified size, and the table rows and columns fit within this specified size, the border edges (for selections or custom borders) that are expected to be drawn where the top or left overlay finishes, are not drawn.

I have investigated why this happens. The row and column calculators calculate `startRow` and `startColumn` in reverse mode. This turns out to set the value `0` for `startRow` and `startColumn`. The problem is, that that value should NOT be 0, if `fixedRowsTop` and `fixedColumnsLeft` are set.

Because the value is 0, we have several bad side effects:
- the master table renders duplicate rows and columns that are also rendered on the top and left overlays
- the method `getFirstVisibleRow` and `getFirstVisibleColumn` on master table will return 0, too. Which is wrong, because these rows and columns are clearly not visible if they are obstructed by an overlay

### Steps to reproduce

1. Set up a big contiainer
2. Within that container, have a small table
3. The table should have `fixedRowsTop` and `fixedColumnsLeft`
4. Make a selection on the master table, at the edge of the overlays
5. Notice that the top and left border is not drawn

### Demo

https://jsfiddle.net/c80bkeo2/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 77, FF
* Operating System: MacOS

<img width="427" alt="Screenshot 2019-10-28 at 00 22 51" src="https://user-images.githubusercontent.com/566463/67643690-5e6a4700-f91a-11e9-8670-6e1ee9f43547.png">

**Comment by warpech** [comment]
This problem also can be observed exactly with the same steps after the rewrite of borders to SVG (https://github.com/handsontable/handsontable/pull/6157)

For a few days I was working on fixing it, because I thought it is a regression, but it turns out it is an old problem, so I will leave it out of the scope of https://github.com/handsontable/handsontable/pull/6157.

**Comment by warpech** [comment]
This issue is fixed by the introduction of "frozen line" in SVG borders PR https://github.com/handsontable/handsontable/pull/6157

Was:

![image](https://user-images.githubusercontent.com/566463/76432350-26d4d680-63b3-11ea-8843-16cadb5238a7.png)

Is:

![image](https://user-images.githubusercontent.com/566463/76432383-32c09880-63b3-11ea-92c8-88414b6ec764.png)

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/x2w5same/

**Comment by AMBudnik** [comment]
We get the same effect in v8.2.0 https://jsfiddle.net/handsoncode/L3mszge9/

**Comment by KrzysztofZie** [comment]
It has been fixed in the develop branch.
It will be released along with the latest version of the library
