### ISSUE TITLE
The list of values in Filter by value is incomplete if we use nestedRows

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6858]
### Description

The list of values in `Filter by value` is incomplete if we use `nestedRows`.

**Important**: Before version 8.0.0.-beta1 only the first parent was visible, so the scenario of having those values only
* blank cells
* Best Rock Performance

was understandable and showed the exact list of options available. However, after fixing the issue and bringing back all the rows this result is no longer valid.

### Steps to reproduce

1. Open 'Filter by value' for the first column

![81551315-e9c09c80-9381-11ea-9de6-a7b650377dd4](https://user-images.githubusercontent.com/10757813/81553953-3dcd8000-9386-11ea-9915-6a335280fc54.png)

**Expected result**
You should see the following list
* blank cells
* Best Rock Performance
* Best Metal Performance
* Best Rock Song
* Best Rock Album

**Actual result**
* blank cells
* Best Rock Performance

### Demo

https://jsfiddle.net/naovL92p/ 8.0.0.-beta1 (broken)
https://jsfiddle.net/9phsmtrL/1/ 8.0.0.-beta2-rev2 (broken)

### Related
https://github.com/handsontable/handsontable/issues/5889

### Your environment
* Handsontable version: 8.0.0.-beta1
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
@wojciechczerniak @wszymanski We have discussed this subject and we should take off the `regression` label. I have assumed that the list of values was correct as it showed the exact number of values, however, it should show all the values.

**Comment by budnix** [comment]
The bug has been at least since 7.2.0. Meanwhile, some of the rendering issues were fixed leaving the filter values component incomplete. This is not a regression so I removed a label.

**Comment by AMBudnik** [comment]
A note to description

The list is complete if we collapse the parents

![Zrzut ekranu 2020-07-17 o 11 31 53](https://user-images.githubusercontent.com/10757813/87771855-33fe4800-c821-11ea-8df7-193f86c153d0.png)

**Comment by AMBudnik** [comment]
The issue remains the same using v 8.0.0 https://jsfiddle.net/9veh8nmq/

**Comment by AMBudnik** [comment]
This issue is still replicable in v 8.2.0 https://jsfiddle.net/y5rnx07d/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **NestedRows grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7510

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
### Case 2

Demo https://jsfiddle.net/smhz4ogx/6/ 

We have the `test` value from cell `29, 0` in the `Filter by value` list. However, `test2` from cell `30, 0` is missing.

![image](https://user-images.githubusercontent.com/10757813/127982084-d368831f-4e65-4977-a0c6-1a20cf63891c.png)

_Observation: Changing the height of rows or adding `renderAllRows` does not change anything._

`Inform Zen # 26789`

**Comment by corsantic** [comment]
any updates?

**Comment by AMBudnik** [comment]
Hi @corsantic 

this issue is closed as it is a part of the scope of #7510 It hasn't been scheduled or fixed yet.
I will set myself a reminder to update you as soon as we fix it.
