### ISSUE TITLE
Custom borders on a fixed column don't render correctly

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7059]
### Description

Custom border is misaligned when columns are hidden and columns are fixed.

### Steps to reproduce

1. Check the yellow border between the versions

**7.4.2** 
![Zrzut ekranu 2020-06-29 o 15 36 07](https://user-images.githubusercontent.com/10757813/86012476-4fdead00-ba1e-11ea-94cb-8a6e608fd0d3.png)

**8.0.0-beta2-rev5+**
![Zrzut ekranu 2020-06-29 o 15 36 20](https://user-images.githubusercontent.com/10757813/86012494-566d2480-ba1e-11ea-9978-3f8d05aa4ff4.png)

### Demo

https://jsfiddle.net/ft015zsy/2/ 7.4.2 (working)
https://jsfiddle.net/51pzore4/ 8.0.0-beta2-rev4 (working)
https://jsfiddle.net/ft015zsy/1/ 8.0.0-beta2-rev5 (**broken**)
https://jsfiddle.net/0785Lxq1/ 8.0.0-beta2-rev17 (broken)

### Your environment
* Handsontable version: 8.0.0-beta2-rev5 
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by aninde** [comment]
This issue is no longer replicable in `8.0.0-beta2-rev20`https://jsfiddle.net/aninde/tzjb9n6m/ 
`Rev20` introduced a breaking change. Hiding cells at the start or at the end of a range will also hide the border. 
Details are described here https://github.com/handsontable/handsontable/pull/7083 

<img width="202" alt="Screenshot 2020-07-08 at 12 06 32" src="https://user-images.githubusercontent.com/30186818/86906244-8f3e8500-c113-11ea-8f40-40fb6ed7c5e2.png">

**Comment by aninde** [comment]
The original description of this issue is related to regression found in `8.0.0`. This regression was fixed, but we agrred that this bug is related to the earlier version of Handsontable, so I reopen this issue with changed cases.

Custom borders on edges of fixed columns don't render correctly. This can be seen especially when the columns are also hidden.
CustomBorder is overlapped by fixed overlay and display order (z-index) is incorrect.

https://jsfiddle.net/aninde/fxzjc9vo/ `v7.4.2`
**Case 1**
Wrong order - https://jsfiddle.net/aninde/7yaqkvp5/
Red small border on D3  shouldn't be under orange.

![image](https://user-images.githubusercontent.com/30186818/86911626-ea747580-c11b-11ea-97aa-60cd8abed3d6.png)


**Case 2**
Cutted border https://jsfiddle.net/aninde/gk5os6hb/
Red border should have 3px thicknesses. As you can see it has less, it is cut off by overlapping.

![image](https://user-images.githubusercontent.com/30186818/86911633-efd1c000-c11b-11ea-8347-d9a02735f0d1.png)

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. It's even worse than in the beta version -the yellow border doesn't appear.
![Zrzut ekranu 2020-08-27 o 10 33 44](https://user-images.githubusercontent.com/1555809/91417776-90597c00-e851-11ea-8e84-a9c6db0263be.png)

Here's an updated demo - https://jsfiddle.net/dspq0jt2/

**Comment by wojciechczerniak** [comment]
@pnowak @AMBudnik It's not worse. That was an intended change made in #7083. Is mentioned in the RN.

**Comment by AMBudnik** [comment]
@wojciechczerniak #7083 mentions hidden cells. Does it apply for fixing as well (our case)?

**Comment by wojciechczerniak** [comment]
@AMBudnik You would need a demo without hidden columns, but no, it does not.

This will be "fixed" by SVG borders. @warpech introduced there a "fixed line" that covers the borders. So nothing will change in the border rendering but it will look good.
