### ISSUE TITLE
[8.0.0-beta2-rev1] inconsistency beetween contextMenu and dropdownMenu when all rows are trimmed

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7060]
### Description
In the situation where all rows are trimmed, some options are available in `contextMenu` opened from column Header and not available in equivalent `dropdownMenu`.

**Actual result:**
Insert row below is avaliable from `contextMenu` in `8.0.0-beta2+`
<img width="259" alt="Screenshot 2020-06-29 at 15 48 50" src="https://user-images.githubusercontent.com/30186818/86014612-d98f7a00-ba20-11ea-8fea-fbc7d0880278.png">
<img width="263" alt="Screenshot 2020-06-29 at 15 48 59" src="https://user-images.githubusercontent.com/30186818/86014618-db593d80-ba20-11ea-8caf-14b6b4fc607b.png">

**Expected result:**
like in `7.4.2`
Insert row below isn't avaliable like in `dropDownMenu`
<img width="283" alt="Screenshot 2020-06-29 at 15 53 25" src="https://user-images.githubusercontent.com/30186818/86014624-ddbb9780-ba20-11ea-845a-03870a29e12b.png">
<img width="268" alt="Screenshot 2020-06-29 at 15 53 32" src="https://user-images.githubusercontent.com/30186818/86014634-df855b00-ba20-11ea-921c-d17fe54c03f4.png">

### Demo

https://jsfiddle.net/aninde/vm8u2ert/ `8.0.0-beta2-rev1` - broken
https://jsfiddle.net/aninde/9ka0mt17/  `8.0.0-beta2-rev17` - broken
https://jsfiddle.net/aninde/bzfxmeLw/ - `8.0.0-beta.1`-  fixed
https://jsfiddle.net/aninde/1w6Lk8oy/ - `7.4.2` - fixed

### Your environment
* Handsontable version: `8beta2+`
* Browser Name and version: Firefox
* Operating System: macOS Catalina 10.15

**Comment by budnix** [comment]
The issue should be fixed by PR https://github.com/handsontable/handsontable/pull/7027

**Comment by aninde** [comment]
I had such a hope, but unfortunately it still appears on `8.0.0-beta2-rev18`https://jsfiddle.net/aninde/oc4u97kq/
<img width="329" alt="Screenshot 2020-06-30 at 16 18 36" src="https://user-images.githubusercontent.com/30186818/86137484-9ea74800-baed-11ea-869f-e2058ad26001.png">

**Comment by budnix** [comment]
It seems that this bug is fixed already. I've tested it with `develop` branch and everything looks good https://jsfiddle.net/budnix/L470v1p6/.

**Comment by aninde** [comment]
Expected result:
contextMenu on column A
<img width="352" alt="Screenshot 2020-07-06 at 14 29 05" src="https://user-images.githubusercontent.com/30186818/86593246-24ffd600-bf95-11ea-8f8e-1617119f78a0.png">

Actual result from https://github.com/handsontable/handsontable/issues/7060#issuecomment-654202514 
<img width="344" alt="Screenshot 2020-07-06 at 14 30 47" src="https://user-images.githubusercontent.com/30186818/86593339-4fea2a00-bf95-11ea-8b9f-5a6fcbf1b60a.png">

**Comment by budnix** [comment]
@aninde @wojciechczerniak confirmed that in that case the "Insert row below" should be disabled.

**Comment by aninde** [comment]
Is fixed by `8.0.0-beta2-rev22` https://jsfiddle.net/aninde/a0ft3o8u/
