### ISSUE TITLE
Hidden columns reappear if we run updateSettings

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7165]
> Hey. I am having this issue too as the title describes but the reproduction steps are different. If you want me to make a separate issue then let me know but I searched for existing issues first and found this. This issue seems to be happening in the 8.0.0-beta2-rev1 as well.
> 
> My reproduction steps:
> 1. Enable HiddenColumns
> 2. Manually hide some columns using the plugin methods.
> 3. Call updateSettings()
> 4. Columns reappear
> 
> They do not reappear if specified in the original options for the table.
> 
> Example: http://jsfiddle.net/meja7421/ (You will see the columns reappear after 3 seconds when updateSettings() is run)
> 
> Thanks

_Originally posted by @jeremy-smith-maco in https://github.com/handsontable/handsontable/issues/4121#issuecomment-638555212_

inform forum https://forum.handsontable.com/t/column-hiding-leads-to-ghosting-of-empty-columns/5223 and Gr https://handsoncode.groovehq.com/tickets/31941

**Comment by giorgitus** [comment]
will this problem be fixed in the next build?
To avoid this i set every time the hiddens columns but in my application (several times) if I do an updatesettings with this parameter 
hiddenColumns: { columns:[] } I recive this error:
![Schermata 2020-10-20 alle 11 45 58](https://user-images.githubusercontent.com/56067680/96570211-5c875980-12ca-11eb-8a7d-caecc60602fa.png)

If I look in the source code
![Schermata 2020-10-20 alle 12 41 01](https://user-images.githubusercontent.com/56067680/96575846-9445cf80-12d1-11eb-9347-03ad1ac69336.png)
I see that rows has an undefined element. When it can contains an "undefined" element? 

I tried to replicate in jsfiddle but I wasn't able to reproduce it. I don't know if the problem can be correlated with this issue. Any ideas?

**Comment by AMBudnik** [comment]
Hi @giorgitus at the first glance it does not look like the same issue. Can you tell me a bit more about your settings/options? We can discuss this over email - support@handsontable.com

**Comment by AMBudnik** [comment]
The issue is still replicable using v11.0.1 https://jsfiddle.net/8yqmv9ht/

**Comment by aninde** [comment]
Fixed by v12.0.0. Updated working demo https://jsfiddle.net/Lonbvf7z/.

**Comment by warpech** [comment]
Notify https://github.com/handsontable/handsontable/issues/7391
