### ISSUE TITLE
[9.0.0] Nested rows don't work well while HyperFormula is enabled as formulas engine

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8048]
### Description
Nested rows don't work with the new engine of formulas.

**Some of the bugs:**
1. Detaching from parent returns blank cell.
2. After collapsing and uncollapsing, wrong values are returned.
3. Undoing of row removal don't work.
4. Autofill doesn't work and breaks the table due to the error in the console.
3. All inserting options from `context menu` or `drop-down menu` doesn't work and the console throws error:
```
CrudOperations.js:352 Uncaught Error: Invalid arguments, expected an array of arrays or a raw cell value.
    at CrudOperations.setCellContents (CrudOperations.js:352)
    at HyperFormula.setCellContents (HyperFormula.js:344)
    at Formulas.onModifySourceData (formulas.mjs:454)
    at Core.eval (formulas.mjs:266)
    at Hooks.run (pluginHooks.mjs:190)
    at Core.runHooks (core.mjs:2101)
    at DataSource.setAtCell (dataSource.mjs:132)
    at eval (core.mjs:1535)
    at arrayEach (array.mjs:133)
    at Core.setSourceDataAtCell (core.mjs:1533)
    at DataManager.addChildAtIndex (dataManager.mjs:368)
    at DataManager.addSibling (dataManager.mjs:392)
    at Core.row_above (contextMenu.mjs:128)
    at eval (commandExecutor.mjs:81)
    at arrayEach (array.mjs:133)
    at CommandExecutor.execute (commandExecutor.mjs:80)
    at ContextMenu.executeCommand (contextMenu.mjs:277)
    at Menu.eval (contextMenu.mjs:207)
    at eval (localHooks.mjs:24)
    at arrayEach (array.mjs:133)
    at Menu.runLocalHooks (localHooks.mjs:23)
    at Menu.executeCommand (menu.mjs:330)
    at Core.beforeOnCellMouseUp (menu.mjs:196)
    at Hooks.run (pluginHooks.mjs:190)
    at Core.runHooks (core.mjs:2101)
    at Object.onCellMouseUp (tableView.mjs:584)
    at Settings.getSetting (settings.mjs:143)
    at Walkontable.getSetting (core.mjs:179)
    at Event.onMouseUp (event.mjs:205)
    at HTMLDivElement.eval (event.mjs:90)
    at HTMLDivElement.callbackProxy (eventManager.mjs:45)
```

Demo v(pre)9.0.0 from this PR + HyperFormula 0.6.0 https://codesandbox.io/s/nestedrows-withhyperformula-k81xx

Old engine for comparison v8.4.0 https://codesandbox.io/s/nestedrows-with-formulas-forked-xv8s6

### Steps to reproduce

1. Collapse all parents.
2. Uncollapse them.

### Demo

https://codesandbox.io/s/nestedrows-withhyperformula-k81xx

### Your environment
* Handsontable version: v9.0.0 from [PR ](https://github.com/handsontable/handsontable/pull/7648)+ HF v.0.6.0
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by nikersify** [comment]
Could be because we use visual indexes to retrieve values from hf, https://github.com/handsontable/handsontable/pull/7648#discussion_r633611958

**Comment by nikersify** [comment]
After https://github.com/handsontable/handsontable/pull/8067 (https://github.com/handsontable/handsontable/pull/8067/commits/abf1880eb8d2863e6f92e25afc62a24e1e986f58) it seems like basic collapsing/uncollapsing is fixed at least, but there's still a lot more problems, such as undo of row removal crashing the table, autofill not working with the correct indexes when folds are folded, detaching from parents still returning a blank row and the insert options still crashing the table.

**Comment by aninde** [comment]
Collapsing and uncollapsing works in v9.0.0. https://jsfiddle.net/aninde/vzf2e0bg/
The rest of the bugs persist, so we don't close the issue. This case will need to be carefully investigated later.

**Comment by nikersify** [comment]
I took a shot at this but gave up quickly as it was too difficult for me. From what I found:
- [x] Detaching from parent returns blank cell - it seems like this already wasn't working in the old plugin (throws: `rowObj` is undefined)
- [x] After collapsing and uncollapsing, wrong values are returned - fixed in https://github.com/handsontable/handsontable/commit/abf1880eb8d2863e6f92e25afc62a24e1e986f58
- [x] Autofill doesn't work and breaks the table due to the error in the console - works now
- [ ] All inserting options from context menu or drop-down menu doesn't work and the console throws an error - still happens
- [ ] Undoing of row removal don't work - still doesn't

**Comment by aninde** [comment]
All cases from this issue will be fixed by v10.
http://jsfiddle.net/tpa2q4z5/
