### ISSUE TITLE
New docs: Installation page throws errors

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8301]
### Description
Open with console https://dev.handsontable.com/docs/next/installation/#overview

![Screenshot 2021-06-25 at 09 39 56](https://user-images.githubusercontent.com/30186818/123389596-53a60080-d59a-11eb-980c-9549538beda9.png)

**Comment by budnix** [comment]
The issue is solved by https://github.com/handsontable/handsontable/pull/8302.

**Comment by Siemienik** [comment]
>The issue is solved by #8302.

@budnix, unfortunately not. Issue still exists even #8302 was merged, and the CI deploy passes.

**Comment by budnix** [comment]
@Siemienik true. On the current https://dev.handsontable.com/docs/next/installation/#overview page, there is still a problem with 404 `https://dev.handsontable.com/img/search.svg (404)`. I think that this causes the error.

**Comment by budnix** [comment]
The 404 error happens on Theme switching.

**Comment by budnix** [comment]
Found it. The entry https://github.com/handsontable/handsontable/blob/feature/issue-7624/docs/.vuepress/theme/styles/theme-dark.styl#L44 need to be fixed as well :)

**Comment by Siemienik** [comment]
> @Siemienik true. On the current https://dev.handsontable.com/docs/next/installation/#overview page, there is still a problem with 404 `https://dev.handsontable.com/img/search.svg (404)`. I think that this causes the error.

That problem is solved in #8309 

Nevertheless, the Issue reported by @aninde still exists. It is caused by [Code groups and code blocks](https://vuepress.vuejs.org/theme/default-theme-config.html#code-groups-and-code-blocks). I have no idea why it is, and how to fix it. For that purpose, I would like to ignore this error or remove `<code-group>`

**Comment by budnix** [comment]
The same errors are thrown on the [official Vuepress page](https://vuepress.vuejs.org/theme/default-theme-config.html#code-groups-and-code-blocks) 🤣
